const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM,VirtualConsole}=require('jsdom'),C=require('../dist/compensation-engine.js'),dir=path.join(__dirname,'../dist');
const saudi={mode:'saudi',asOf:'2026-10-05',regime:'saudi-new',applicabilityConfirmed:true,sanedEligible:true,housingMonthly:2500,otherMonthly:500,contributoryExtraMonthly:'',medicalAnnual:6000,serviceYears:7,eosWageMonthly:''};
const base={...C.example,role:'Software engineer',grade:'G07',bandMin:8000,bandMid:10000,bandMax:12000,currentSalary:10000,oncostPercent:0};
const settle=()=>new Promise(r=>setTimeout(r,10));
async function app(locale='en',setup=null){
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));const dom=new JSDOM('<!doctype html><html lang="'+locale+'"><body><h1 id="enterprise-heading"></h1><span id="breadcrumb-title"></span><div id="ent-content"></div></body></html>',{url:'https://example.test/#enterprise/compensation',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});
 const w=dom.window;w.HTMLElement.prototype.scrollIntoView=()=>{};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};
 w.MiyarEnterpriseCore={csv:()=>[]};setup?.(w);for(const name of ['scenario-workspace.js','compensation-engine.js','compensation-workbench.js','audit-improvements.js'])w.eval(fs.readFileSync(path.join(dir,name),'utf8'));await settle();return {w,d:w.document,dom,errors,edit:(id,value)=>{const el=w.document.getElementById('cp-'+id);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));},run:()=>w.document.querySelector('[data-cp-run]').click()};
}

test('Saudi optional monetary components are zero when blank and expert cost remains 194125',()=>{
 const v=C.evaluate({...base,employerCosts:saudi});assert.equal(v.result.annualEmployerCost,194125);assert.equal(v.employerBreakdown.contributoryExtraMonthly,0);
 for(const key of ['housingMonthly','otherMonthly','contributoryExtraMonthly','medicalAnnual'])for(const value of ['',null,undefined,'   '])assert.deepEqual(C.saudiCost(10000,'monthly',{...saudi,[key]:value}),C.saudiCost(10000,'monthly',{...saudi,[key]:0}));
 for(const key of ['housingMonthly','otherMonthly','contributoryExtraMonthly','medicalAnnual'])assert.throws(()=>C.saudiCost(10000,'monthly',{...saudi,[key]:'nonsense'}),/valid number/);
 assert.throws(()=>C.saudiCost(10000,'monthly',{...saudi,serviceYears:''}),/Completed service years/);
});

test('each GOSI branch carries rate, monthly base, annual amount, source and selected effective date',()=>{
 const b=C.saudiCost(10000,'monthly',saudi);assert.equal(b.gosiComponents.length,3);assert.deepEqual(b.gosiComponents.map(x=>[x.id,x.rate,x.monthlyBase,x.annualAmount,x.effectiveFrom]),[['pension',10,12500,15000,'2026-07-01'],['saned',.75,12500,1125,'2024-07-03'],['occupational',2,12500,3000,'2024-07-03']]);
 assert.equal(b.gosiComponents.reduce((s,x)=>s+x.annualAmount,0),b.annualGosi);for(const x of b.gosiComponents){assert.match(x.source.url,/gosi.gov.sa/);assert.equal(x.appliedAsOf,'2026-10-05');}
 const legacy=C.saudiCost(10000,'monthly',{...saudi,regime:'saudi-existing'});assert.equal(legacy.gosiComponents[0].effectiveFrom,null);assert.equal(legacy.gosiComponents[1].effectiveFrom,'2022-01-01');
});

test('midpoint belongs to Q2; zero input has positive-value error and blank currency cannot become SAR silently',()=>{
 assert.equal(C.evaluate(base).result.currentQuartile,'Q2');for(const key of ['bandMin','bandMid','bandMax','headcount','currentSalary'])assert.throws(()=>C.evaluate({...base,[key]:0}),e=>e.code==='POSITIVE_NUMBER'&&/greater than zero/.test(e.message));
 for(const currency of ['',null,undefined,' '])assert.throws(()=>C.evaluate({...base,currency}),e=>e.field==='currency'&&/required/.test(e.message));assert.equal(C.evaluate({...base,currency:' sar '}).input.currency,'SAR');
});

test('roster compression identifies near-manager salary and inversion without turning a review trigger into approval',()=>{
 const v=C.evaluate({...base,incumbents:[{id:'P001',currentSalary:10000},{id:'P002',currentSalary:9500,managerId:'P001'},{id:'P003',currentSalary:11000,managerId:'P001'},{id:'P004',currentSalary:9000,managerSalary:10000},{id:'P005',currentSalary:8500,managerId:'P099'}]});
 assert.deepEqual(v.rosterDiagnostics.compression.map(x=>[x.id,x.status]),[['P002','salary-compression'],['P003','salary-inversion'],['P004','salary-compression']]);assert.deepEqual(v.rosterDiagnostics.unresolvedManagers,[{id:'P005',managerId:'P099'}]);assert.equal(v.rosterDiagnostics.byGrade[0].count,5);assert.match(v.rosterDiagnostics.notice,/do not establish/);
});

test('grade roster calculates dispersion and flags actual employees below and above entered bands',()=>{
 const v=C.evaluate({...base,rosterCsv:'id,currentSalary,grade,managerId,bandMin,bandMid,bandMax,bandSource\nP001,7500,G07,,,,,\nP002,12500,G07,P001,,,,\nP003,19000,G08,,15000,18000,21000,Approved G08 band policy'});
 assert.equal(v.rosterDiagnostics.byGrade.length,2);const g=v.rosterDiagnostics.byGrade.find(x=>x.grade==='G07');assert.equal(g.dispersionReview,true);assert.deepEqual(g.outOfBand.map(x=>[x.id,x.status]),[['P001','below-minimum'],['P002','above-maximum']]);assert.equal(v.incumbents[2].input.bandMid,18000);assert.equal(v.incumbents[2].input.grade,'G08');
 assert.throws(()=>C.evaluate({...base,incumbents:[{id:'P001',currentSalary:9000,bandMin:8000}]}),/need minimum, midpoint, maximum and source/);
 assert.throws(()=>C.evaluate({...base,incumbents:[{id:'P001',currentSalary:9000,managerId:'P001'}]}),/own manager/);
 assert.throws(()=>C.evaluate({...base,rosterCsv:'id,currentSalary,managerId\nP001,9000,512345678'}),e=>e.code==='ROSTER_PRIVACY');
});

for(const locale of ['en','ar'])test('compensation feedback focuses and associates first invalid field, then shows Q2 and two-decimal ratio '+locale,async()=>{
 const a=await app(locale);try{a.d.querySelector('[data-cp-example]').click();a.edit('current','30000');a.edit('min','0');a.run();assert.equal(a.d.activeElement.id,'cp-min');assert.equal(a.d.getElementById('cp-min').getAttribute('aria-invalid'),'true');assert.equal(a.d.getElementById('cp-min').getAttribute('aria-errormessage'),'cp-message');assert.match(a.d.querySelector('[data-cp-message]').textContent,locale==='ar'?/أكبر من صفر/:/greater than zero/);assert.equal(a.d.querySelector('.cp-result'),null);
 a.edit('min','24000');a.run();assert.ok(a.d.querySelector('.cp-result'));assert.equal(a.d.getElementById('cp-min').hasAttribute('aria-invalid'),false);assert.match(a.d.querySelector('.cp-result').textContent,locale==='ar'?/١٫٠٠/:/1\.00/);assert.match(a.d.querySelector('.cp-result').textContent,locale==='ar'?/الربع الثاني/:/Second range quartile/);assert.equal(a.d.activeElement.getAttribute('data-cp-result'),'');assert.equal(a.d.querySelector('[data-cp-run]').parentElement.nextElementSibling?.hasAttribute('data-cp-result'),true);assert.equal(a.errors.length,0);
 }finally{a.dom.window.close();}
});

for(const locale of ['en','ar'])test('blank contributory input calculates and exposes every GOSI rate with date in the UI '+locale,async()=>{
 const a=await app(locale);try{a.d.querySelector('[data-cp-example]').click();for(const [k,v] of Object.entries({min:8000,mid:10000,max:12000,current:10000,oncost:0,housing:2500,othercash:500,contributory:'',medical:6000,service:7,regime:'saudi-new'}))a.edit(k,String(v));for(const id of ['saudi','applicability','saned'])a.d.getElementById('cp-'+id).checked=true;a.run();assert.ok(a.d.querySelector('.cp-result'));const rows=a.d.querySelectorAll('.cp-gosi-components tbody tr');assert.equal(rows.length,3);assert.match(rows[0].textContent,/10%/);assert.match(rows[0].textContent,/2026-07-01/);assert.match(rows[1].textContent,/0.75%/);assert.equal(rows[0].querySelector('a').hostname,'awareness.gosi.gov.sa');assert.equal(a.w.MiyarCompensationWorkbench.getCostContext().annualEmployerCostPerFte,194125);assert.equal(a.w.MiyarCompensationWorkbench.getCostContext().scope,'guest');assert.equal(a.errors.length,0);
 }finally{a.dom.window.close();}
});

test('approved-band missing feedback names the requested grade near the action',async()=>{const a=await app();try{a.edit('grade','G01');a.d.querySelector('[data-band-apply]').click();assert.match(a.d.querySelector('#audit-band-status').textContent,/No approved band for grade G01/);assert.match(a.d.querySelector('[data-cp-message]').textContent,/Import the salary-band file/);assert.equal(a.d.querySelector('[data-audit-bands]').open,true);}finally{a.dom.window.close();}});

test('Arabic example role and grade are translated without relying on delayed global localization',async()=>{const a=await app('ar');try{a.d.querySelector('[data-cp-example]').click();assert.equal(a.d.getElementById('cp-role').value,'مدير مشاريع وعمليات رأس المال البشري');assert.equal(a.d.getElementById('cp-grade').value,'G11 · مدير');}finally{a.dom.window.close();}});

test('compensation publishes exact position revision and clears stale cost context when inputs change',async()=>{const a=await app();try{a.d.querySelector('[data-cp-example]').click();a.w.MiyarCompensationWorkbench.setPositionContext({positionId:'POS-17',revision:3,title:C.example.role,grade:C.example.grade,jobFamily:'Human Capital'});a.run();const context=a.w.MiyarCompensationWorkbench.getCostContext();assert.equal(context.positionId,'POS-17');assert.equal(context.revision,3);assert.equal(context.grade,'G11');assert.equal(context.annualEmployerCostPerFte,414000);assert.match(a.d.querySelector('[data-cp-position-context]').textContent,/v3/);a.edit('mid','31000');assert.equal(a.w.MiyarCompensationWorkbench.getCostContext(),null);}finally{a.dom.window.close();}});

test('explicit reviewed-range action transfers only the selected position revision and records its source and planning midpoint',async()=>{
 const a=await app();try{
  a.edit('role','Software engineer');a.edit('grade','G03');
  a.w.MiyarCompensationWorkbench.setPositionContext({positionId:'ORG-POS-3',revision:4,title:'Software engineer',jobFamily:'Software development',grade:'G03',headcount:2,band:{min:7000,max:11000,currency:'SAR',period:'monthly',source:'Approved Total Rewards committee evidence for revision 4'}});
  assert.equal(a.d.getElementById('cp-min').value,'');a.d.querySelector('[data-cp-reviewed-band]').click();
  assert.equal(a.d.getElementById('cp-min').value,'7000');assert.equal(a.d.getElementById('cp-mid').value,'9000');assert.equal(a.d.getElementById('cp-max').value,'11000');assert.equal(a.d.getElementById('cp-source').value,'Approved Total Rewards committee evidence for revision 4');assert.equal(a.d.getElementById('cp-headcount').value,'2');assert.match(a.d.querySelector('[data-cp-position-context]').textContent,/planning assumption/);
  a.run();const context=a.w.MiyarCompensationWorkbench.getCostContext();assert.equal(context.positionId,'ORG-POS-3');assert.equal(context.revision,4);assert.equal(context.grade,'G03');assert.equal(context.annualEmployerCostPerFte,108000);assert.equal(context.totalEmployerCost,216000);assert.equal(context.bandBinding.midpointBasis,'planning-range-centre');assert.equal(context.bandSource,'Approved Total Rewards committee evidence for revision 4');
  a.d.querySelector('[data-cp-reviewed-band]').click();assert.equal(a.w.MiyarCompensationWorkbench.getCostContext(),null);a.run();assert.equal(a.w.MiyarCompensationWorkbench.getCostContext().positionId,'ORG-POS-3');a.d.querySelector('[data-cp-example]').click();assert.equal(a.w.MiyarCompensationWorkbench.getCostContext(),null);a.run();assert.equal(a.w.MiyarCompensationWorkbench.getCostContext().positionId,'');assert.equal(a.w.MiyarCompensationWorkbench.getCostContext().bandBinding,null);assert.equal(a.d.querySelector('[data-cp-reviewed-band]'),null);
 }finally{a.dom.window.close();}
});

test('position range without a reviewed source cannot masquerade as a transferable approved band',async()=>{const a=await app();try{a.edit('role','Software engineer');a.edit('grade','G03');a.w.MiyarCompensationWorkbench.setPositionContext({positionId:'ORG-POS-3',revision:4,title:'Software engineer',grade:'G03',band:{min:7000,max:11000,currency:'SAR',period:'monthly'}});assert.equal(a.d.querySelector('[data-cp-reviewed-band]'),null);assert.equal(a.d.getElementById('cp-min').value,'');}finally{a.dom.window.close();}});

for(const locale of ['en','ar'])test('fresh compensation uses only an actual reviewed position, explains the source and lets the user undo automatic fill '+locale,async()=>{
 const context={positionId:'ORG-APPROVED-3',id:'ORG-APPROVED-3',revision:2,title:'Software engineer',jobFamily:'Software development',headcount:3,grade:'G03',authority:'approved-rewards',band:{min:8000,max:12000,currency:'SAR',period:'monthly',source:'Approved Rewards evidence rev2'}};
 const a=await app(locale,w=>{w.MiyarEnterprise={positionContext:()=>context,session:()=>null};});try{assert.equal(a.d.getElementById('cp-min').value,'8000');assert.equal(a.d.getElementById('cp-mid').value,'10000');assert.equal(a.d.getElementById('cp-headcount').value,'3');assert.equal(a.d.querySelector('[data-cp-essentials]').querySelectorAll('input,select').length,7);assert.equal(a.d.querySelector('[data-cp-position-panel]').open,false);a.w.MiyarCompensationWorkbench.render();a.w.MiyarCompensationWorkbench.render();assert.equal(a.d.getElementById('cp-min').value,'8000');assert.equal(a.d.querySelector('[data-cp-position-panel]').open,false);assert.match(a.d.querySelector('[data-cp-source-review]').textContent,locale==='ar'?/تعبئة تلقائية/:/Automatically filled/);assert.equal(a.d.querySelector('[data-cp-cost-panel]').open,false);assert.equal(a.d.querySelector('[data-cp-progression-panel]').open,false);assert.equal(a.d.getElementById('cp-saudi').closest('details').open,false);a.d.querySelector('[data-cp-undo-fill]').click();assert.equal(a.d.getElementById('cp-min').value,'');a.edit('min','9000');a.w.MiyarCompensationWorkbench.render();assert.equal(a.d.getElementById('cp-min').value,'9000');assert.equal(a.errors.length,0);}finally{a.dom.window.close();}
});

test('local preliminary review keeps the range empty until the user explicitly imports it',async()=>{const context={positionId:'LOCAL-EXAMPLE',id:'LOCAL-EXAMPLE',revision:2,title:'Software engineer',grade:'G03',authority:'local-review-proposal',band:{min:8000,max:12000,currency:'SAR',period:'monthly',source:'Local illustrative committee range'}};const a=await app('en',w=>{w.MiyarEnterprise={positionContext:()=>context,session:()=>null};});try{assert.equal(a.d.getElementById('cp-min').value,'');assert.ok(a.d.querySelector('[data-cp-reviewed-band]'));assert.equal(a.d.querySelector('[data-cp-source-review]'),null);}finally{a.dom.window.close();}});

test('progressive sections explain why fields matter and reopen whenever their values are active',async()=>{const a=await app();try{assert.match(a.d.getElementById('cp-currency-hint').textContent,/same currency/);assert.match(a.d.getElementById('cp-period-hint').textContent,/monthly × 12/);assert.match(a.d.getElementById('cp-source-hint').textContent,/review the range and its version/);assert.match(a.d.getElementById('cp-current-hint').textContent,/actual pay/);assert.equal(a.d.querySelector('[data-cp-cost-panel]').open,false);assert.equal(a.d.querySelector('[data-cp-progression-panel]').open,false);assert.equal(a.d.querySelector('[data-cp-position-panel]').open,false);assert.equal(a.d.querySelector('[data-cp-essentials]').querySelectorAll('input,select').length,7);a.d.querySelector('[data-cp-example]').click();assert.equal(a.d.querySelector('[data-cp-position-panel]').open,true);assert.equal(a.d.querySelector('[data-cp-cost-panel]').open,true);a.d.getElementById('cp-progression').checked=true;a.d.getElementById('cp-progression').dispatchEvent(new a.w.Event('change',{bubbles:true}));assert.equal(a.d.querySelector('[data-cp-progression-panel]').open,true);}finally{a.dom.window.close();}});

test('unsaved compensation drafts remain bounded to the exact account and position revision',async()=>{
 let context={positionId:'POS-A',id:'POS-A',revision:1,title:'Role A',grade:'G03',authority:'approved-rewards',band:{min:8000,max:12000,currency:'SAR',period:'monthly',source:'Approved Rewards position A revision 1'}},scope='organization-a';
 const a=await app('en',w=>{w.MiyarEnterprise={positionContext:()=>context,session:()=>({scope})};});try{
  a.edit('current','9500');a.w.MiyarCompensationWorkbench.render();assert.equal(a.d.getElementById('cp-current').value,'9500');assert.equal(a.d.getElementById('cp-min').value,'8000');assert.match(a.d.querySelector('[data-cp-source-review]').textContent,/POS-A v1/);a.run();assert.equal(a.w.MiyarCompensationWorkbench.getCostContext().positionId,'POS-A');assert.equal(a.w.MiyarCompensationWorkbench.getCostContext().bandBinding.positionId,'POS-A');
  context={...context,positionId:'POS-B',id:'POS-B',revision:2,title:'Role B',band:{...context.band,min:14000,max:18000,source:'Approved Rewards position B revision 2'}};a.w.dispatchEvent(new a.w.CustomEvent('miyar:position-context'));
  assert.equal(a.d.getElementById('cp-current').value,'');assert.equal(a.d.getElementById('cp-min').value,'14000');assert.match(a.d.querySelector('[data-cp-source-review]').textContent,/POS-B v2/);
  context={...context,positionId:'POS-A',id:'POS-A',revision:1,title:'Role A',band:{...context.band,min:8000,max:12000,source:'Approved Rewards position A revision 1'}};a.w.dispatchEvent(new a.w.CustomEvent('miyar:position-context'));
  assert.equal(a.d.getElementById('cp-current').value,'9500');assert.equal(a.d.getElementById('cp-min').value,'8000');assert.match(a.d.querySelector('[data-cp-source-review]').textContent,/POS-A v1/);
  scope='organization-b';a.w.dispatchEvent(new a.w.CustomEvent('miyar:session'));a.w.MiyarCompensationWorkbench.render();assert.equal(a.d.getElementById('cp-current').value,'');assert.equal(a.w.MiyarCompensationWorkbench.getCostContext(),null);assert.equal(a.errors.length,0);
 }finally{a.dom.window.close();}
});

for(const locale of ['en','ar'])test('a required source hidden in progressive details opens and receives associated error focus '+locale,async()=>{const a=await app(locale);try{for(const [id,value] of Object.entries({min:'8000',mid:'10000',max:'12000'}))a.edit(id,value);assert.equal(a.d.querySelector('[data-cp-position-panel]').open,false);a.run();assert.equal(a.d.querySelector('[data-cp-position-panel]').open,true);assert.equal(a.d.activeElement.id,'cp-source');assert.equal(a.d.getElementById('cp-source').getAttribute('aria-invalid'),'true');assert.equal(a.d.getElementById('cp-source').getAttribute('aria-errormessage'),'cp-message');assert.match(a.d.querySelector('[data-cp-message]').textContent,locale==='ar'?/مصدر نطاق الراتب/:/salary-band source/);}finally{a.dom.window.close();}});

test('undoing smart range fill retains actual pay and benefit inputs entered afterward',async()=>{const context={positionId:'POS-UNDO',revision:1,title:'Role A',grade:'G03',authority:'approved-rewards',band:{min:8000,max:12000,currency:'SAR',period:'monthly',source:'Approved Rewards range for undo example'}};const a=await app('en',w=>{w.MiyarEnterprise={positionContext:()=>context,session:()=>null};});try{a.edit('current','9500');a.edit('oncost','10');a.d.querySelector('[data-cp-undo-fill]').click();assert.equal(a.d.getElementById('cp-min').value,'');assert.equal(a.d.getElementById('cp-source').value,'');assert.equal(a.d.getElementById('cp-current').value,'9500');assert.equal(a.d.getElementById('cp-oncost').value,'10');assert.equal(a.d.querySelector('[data-cp-source-review]'),null);}finally{a.dom.window.close();}});
