const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../dist/enterprise-core.js'),{JSDOM,VirtualConsole}=require('jsdom'),dir=path.join(__dirname,'../dist');
const ref=JSON.parse(fs.readFileSync(path.join(dir,'classifications/ssco-2019.json'))),edu=JSON.parse(fs.readFileSync(path.join(dir,'classifications/education-2020.json'))),skills=JSON.parse(fs.readFileSync(path.join(dir,'classifications/skills.json')));
test('complete supplied occupation tree preserves source conflicts and education leading zeros',()=>{assert.equal(ref.nodes.length,5656);assert.equal(ref.nodes.filter(x=>x.level==='occupation').length,5041);assert.equal(new Set(ref.nodes.map(x=>x.code)).size,5656);assert.equal(C.search(ref.nodes,'٢١٤١٠١')[0].titleAr,'مهندس تخطيط مصانع');assert.equal(C.search(ref.nodes,'۲۱۴۱۱۶')[0].titleAr,'مهندس صناعي عام');assert.equal(ref.validation.missingParents.length,4);assert.equal(edu.fields.length,599);assert.ok(edu.fields.find(x=>x.code==='071903'));});
test('bulk parser preserves quoted newlines, zero scope and duplicate roles',()=>{const rows=C.csv('title,department,occupationCode,directReports,budgetAmount,authority\r\n"مدير, نظام",IT,999999,0,0,يوصي\r\nمهندس برمجيات,IT,251204,0,0,يوصي\r\nمهندس برمجيات,IT,251204,0,0,يوصي\r\n');const r=C.diagnose(rows,ref.nodes,ref.validation.missingParents);assert.equal(r.titleCodeAlignmentPercent,66.7);assert.equal(r.duplicateGroups.length,1);assert.equal(r.scopeAssessableRows,3);assert.equal(r.titleScopeReviewRows,1);assert.throws(()=>C.csv('title,title\na,b'));assert.throws(()=>C.csv('title\n"unclosed'));});
test('skill decomposition catches Arabic conjunctions without pretending model inference',()=>{const r=C.skills('البرمجة وتحليل النظم والتفكير النقدي وSQL',skills);assert.ok(r.some(x=>x.id==='onet:2.B.3.e'));assert.ok(r.some(x=>x.id==='onet:2.B.4.g'));assert.ok(r.some(x=>x.id==='onet:2.A.2.a'));assert.ok(r.some(x=>x.id==='miyar:sql'));});
async function ui(locale='ar'){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));const dom=new JSDOM('<main id="enterprise"></main>',{url:'https://example.test/Miyar/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;w.structuredClone=structuredClone;w.confirm=()=>true;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};w.eval(fs.readFileSync(path.join(dir,'enterprise-document.js'),'utf8'));w.AbortSignal=AbortSignal;w.fetch=async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(dir,String(url))))});w.eval(fs.readFileSync(path.join(dir,'enterprise-core.js'),'utf8'));w.eval(fs.readFileSync(path.join(dir,'enterprise.js'),'utf8'));await w.MiyarEnterprise.mount(w.document.getElementById('enterprise'),{lang:locale});const $=id=>w.document.getElementById('ent-'+id),tab=id=>w.document.querySelector('[data-ent-tab="'+id+'"]').click();return {w,$,tab,errors,dom};}
test('all enterprise sections render in Arabic and English without duplicate IDs',async()=>{for(const lang of ['ar','en']){const a=await ui(lang);try{for(const tab of ['overview','reference','create','workspace','intelligence','bulk','grading','readiness','evidence','market','connection']){a.tab(tab);const ids=[...a.w.document.querySelectorAll('[id]')].map(x=>x.id);assert.equal(new Set(ids).size,ids.length,tab);assert.ok(a.$('content').textContent.trim());}assert.deepEqual(a.errors,[]);}finally{a.dom.window.close();}}});
test('reference search flows into a local draft and restores history without granting approval',async()=>{const a=await ui();try{a.tab('reference');a.$('query').value='٢٥١٢٠٤';a.$('search').click();a.w.document.querySelector('[data-code="251204"]').click();a.$('use-reference').click();assert.equal(a.w.document.querySelector('[data-field="occupationCode"]').value,'251204');a.$('sample').click();a.$('save').click();await new Promise(r=>setImmediate(r));let rows=JSON.parse(a.w.localStorage.getItem(C.KEY));assert.equal(rows.length,1);assert.equal(rows[0].state,'draft');a.tab('workspace');await new Promise(r=>setImmediate(r));a.w.document.querySelector('[data-position]').click();await new Promise(r=>setImmediate(r));assert.equal(a.$('approve'),null);assert.equal(a.$('submit-position'),null);a.$('edit-position').click();let x=a.w.document.querySelector('[data-field="title"]');x.value='<img src=x onerror=alert(1)> Updated';x.dispatchEvent(new a.w.Event('input'));a.$('save').click();await new Promise(r=>setImmediate(r));rows=JSON.parse(a.w.localStorage.getItem(C.KEY));assert.equal(rows[0].revision,2);assert.equal(rows[0].versions.length,2);a.tab('workspace');await new Promise(r=>setImmediate(r));assert.equal(a.w.document.querySelector('img'),null);assert.deepEqual(a.errors,[]);}finally{a.dom.window.close();}});
test('pilot comparison uses paired denominators and distinguishes missing timing',async()=>{const a=await ui('en');try{const r=a.w.MiyarEnterprise.pilotMetrics([{caseId:'1',expectedCode:'251204',miyarCode:'251204',baselineCode:'251104',humanMinutes:'10',miyarMinutes:'4'},{caseId:'2',expectedCode:'251104',miyarCode:'251204',baselineCode:'251104',humanMinutes:'',miyarMinutes:''}]);assert.equal(r.miyarAccuracy,50);assert.equal(r.baselineAccuracy,50);assert.equal(r.timedCases,1);assert.equal(r.timeSavedPercent,60);assert.throws(()=>a.w.MiyarEnterprise.pilotMetrics([{caseId:'1',expectedCode:'a',miyarCode:'a',baselineCode:'a',humanMinutes:'0',miyarMinutes:'1'}]));}finally{a.dom.window.close();}});

test('enterprise free text and complete review package survive save, export and safe draft import',async()=>{
 const a=await ui('en');try{
  a.tab('create');a.$('sample').click();for(const [key,value] of [['field','Health informatics / Digital twins'],['seniority','Principal - 12+ years']]){const x=a.w.document.querySelector('[data-field="'+key+'"]');assert.equal(x.tagName,'INPUT');x.value=value;x.dispatchEvent(new a.w.Event('input'));}
  a.$('save').click();await new Promise(r=>setImmediate(r));const row=JSON.parse(a.w.localStorage.getItem(C.KEY))[0];assert.equal(row.content.field,'Health informatics / Digital twins');assert.equal(row.content.seniority,'Principal - 12+ years');
  a.$('preview-draft').click();const dialog=a.w.document.querySelector('dialog');assert.ok(dialog.open);assert.match(dialog.textContent,/Principal - 12\+ years/);assert.match(dialog.textContent,/Release testing/);a.$('close-report').click();
  const imported=C.importDraft({...row,state:'active',approvals:[{role:'chro'}]});assert.equal(imported.seniority,row.content.seniority);assert.equal(imported.state,undefined);assert.equal(imported.approvals,undefined);
  const doc=require('../dist/enterprise-document.js').html({...imported,title:'<script>alert(1)</script>'},'en');assert.doesNotMatch(doc,/<script>/);assert.match(doc,/&lt;script&gt;/);assert.match(doc,/Draft|draft/);assert.deepEqual(a.errors,[]);
 }finally{a.dom.window.close();}
});
test('unsaved enterprise content cannot be overwritten when the user cancels',async()=>{
 const a=await ui();try{a.tab('create');a.$('sample').click();a.w.confirm=()=>false;a.$('blank').click();assert.equal(a.w.document.querySelector('[data-field="title"]').value,'مهندس برمجيات');a.w.confirm=()=>true;a.$('blank').click();assert.equal(a.w.document.querySelector('[data-field="title"]').value,'');assert.deepEqual(a.errors,[]);}finally{a.dom.window.close();}
});
test('bulk headers and imported matrices reject data loss and invalid content',()=>{
 assert.throws(()=>C.csv('title,المسمى\na,b'));assert.throws(()=>C.csv('title\na,b'));
 for(const content of [{title:'Test',raci:[1]},{title:'Test',headcount:1.5},{title:'Test',directReports:0.5},{title:'Test',provisional:true,occupationCode:'251204'}])assert.throws(()=>C.importDraft({content}));
});

test('complete deployed script bundle opens the enterprise workspace and all local assets exist',async()=>{
 const markup=fs.readFileSync(path.join(dir,'index.html'),'utf8'),errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));
 const dom=new JSDOM(markup,{url:'https://example.test/Miyar/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;
 try{
  w.structuredClone=structuredClone;w.AbortSignal=AbortSignal;w.scrollTo=()=>{};w.confirm=()=>false;w.fetch=async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(dir,String(url))))});
  w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
  for(const x of w.document.querySelectorAll('link[href],script[src]')){const target=x.getAttribute('src')||x.getAttribute('href');assert.ok(fs.existsSync(path.join(dir,target)),target);if(x.tagName==='SCRIPT')w.eval(fs.readFileSync(path.join(dir,target),'utf8'));}
  await new Promise(r=>setImmediate(r));assert.equal(w.document.getElementById('view-enterprise').hidden,false);assert.ok(w.document.getElementById('enterprise-heading'));
  w.document.querySelector('[data-ent-tab="readiness"]').click();assert.match(w.document.getElementById('ent-content').textContent,/متاحة محليًا/);
  w.document.getElementById('language-btn').click();await new Promise(r=>setImmediate(r));assert.match(w.document.getElementById('ent-content').textContent,/Available locally/);
  w.document.getElementById('present-btn').click();assert.ok(w.document.getElementById('presentation').open);for(let i=0;i<6;i++)w.document.getElementById('next-slide').click();assert.match(w.document.getElementById('presentation-content').textContent,/partner/i);
  assert.ok(fs.statSync(path.join(dir,'assets/arabic.ttf')).size>200000);assert.deepEqual(errors,[]);
 }finally{dom.window.close();}
});
