const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const C=require('../dist/compensation-engine'),M=require('../dist/manpower-engine'),E=require('../dist/od-engine'),F=require('../dist/classifications/framework-example.json');
const {assess}=require('../scripts/check-professional-readiness.cjs'),{review}=require('../scripts/review-reference-update.cjs'),crypto=require('node:crypto');
const cases=require('../docs/expert-review/regression-cases.json');
for(const c of cases.cases)test('authored/report-paraphrase scope acceptance: '+c.id,()=>{if(c.id.startsWith('civilEngineering')){const p=E.generate(c.input,c.locale);assert.equal(p.status,'needs-confirmation');assert.ok(p.candidates.some(x=>x.family==='engineering'));}else if(c.expectedBehavior==='block-with-explanation')assert.throws(()=>E.generate(c.input,c.locale),/outside|Unsupported|Unclear|خارج|غير مدعومة|غير واضحة/);else {const p=E.generate(c.input,c.locale);assert.ok(p.content.title);assert.equal(p.gradeRecommendation.status,'pre-evaluation');assert.ok(p.content.kpis.length);assert.equal(new Set(p.content.kpis.map(k=>k.metric)).size,p.content.kpis.length);assert.ok(p.content.kpis.every(k=>k.target!==k.outcome));assert.equal(c.expertApproval,null);}});
test('the expert nursing supervisor and payroll cases carry the right occupation scope and measures',()=>{
 const nurse=E.generate(cases.cases.find(x=>x.id==='nursing-en').input);assert.equal(nurse.content.title,'Nursing Supervisor');assert.equal(nurse.content.finalProposedTitle,nurse.content.title);assert.equal(nurse.validation.find(x=>x.id==='level').status,'warn');assert.match(nurse.content.careerPath,/Nursing Supervisor/);assert.equal(nurse.gradeRecommendation.level,'supervisor');assert.match(nurse.content.qualifications,/nursing/);assert.doesNotMatch(nurse.content.qualifications,/Business|Industrial/);assert.match(nurse.content.kpis[0].metric,/errors.*administrations.*1000/);
 const payroll=E.generate(cases.cases.find(x=>x.id==='payroll-en').input);assert.equal(payroll.content.title,'Payroll Specialist');assert.match(payroll.content.kpis.map(x=>x.outcome).join(' '),/accuracy.*payment.*reconciliation/);assert.doesNotMatch(payroll.content.purpose,/Lead|Oversee/);
});
test('standalone OD and the browser script chain have identical professional outputs',()=>{
 const context=vm.createContext({window:{}});for(const f of ['role-catalog','role-recommender','od-engine','qa-od-v5'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/'+f+'.js'),'utf8'),context);
 for(const id of ['payroll-en','nursing-en','finance-ar']){const c=cases.cases.find(x=>x.id===id);assert.deepEqual(JSON.parse(JSON.stringify(context.window.MiyarODEngine.generate(c.input,c.locale))),JSON.parse(JSON.stringify(E.generate(c.input,c.locale))));}
});
test('expert pay counterexamples produce no unjustified increases, including skewed midpoint',()=>{
 for(const raw of [{currentSalary:25000,headcount:10},{currentSalary:28500},{currentSalary:25000,bandMid:25000}]){const v=C.evaluate({...C.example,...raw});assert.equal(v.result.recommendedSalary,raw.currentSalary);assert.equal(v.result.annualAdjustmentCost,0);assert.equal(v.result.targetSalary,raw.bandMid||30000);}
 const minimum=C.evaluate({...C.example,currentSalary:23000});assert.equal(minimum.result.recommendedSalary,24000);assert.equal(minimum.result.optionalProgressionPerFte,0);
 assert.throws(()=>C.evaluate({...C.example,currentSalary:25000,progressionEnabled:true}),/approved policy/);
 const optional=C.evaluate({...C.example,currentSalary:23000,progressionEnabled:true,progressionApproved:true,progressionPolicy:'TR policy approved by committee',progressionEvidence:'Documented full role proficiency'});assert.equal(optional.result.minimumAdjustmentPerFte,1000);assert.equal(optional.result.optionalProgressionPerFte,6000);assert.equal(optional.result.annualAdjustmentCost,optional.result.annualMinimumAdjustmentCost+optional.result.annualOptionalProgressionCost);
});
test('salary unit checks block zero/unknown currency, and retain an explicit annual confirmation',()=>{
 for(const patch of [{bandMin:0},{currentSalary:0},{currency:'ZZZ'},{headcount:1.5},{period:'weekly'}])assert.throws(()=>C.evaluate({...C.example,...patch}));
 assert.throws(()=>C.evaluate({...C.example,period:'annual'}),/Verify salary period/);const v=C.evaluate({...C.example,period:'annual',unitsConfirmed:true});assert.deepEqual(v.review.warnings,['annual-period-check']);assert.equal(v.result.annualEmployerCost,34500);
});
test('a whole recommended hire has a whole annual budget and fractional cost is separately disclosed',()=>{const v=M.plan(M.example).scenarios.base.final;assert.equal(v.gapHeadcount,1);assert.equal(v.annualGapCost,300000);assert.equal(v.annualFractionalCapacityCost,249211);assert.throws(()=>M.plan({...M.example,capacityPerFte:.001}),/Extreme workforce estimate/);const reviewed=M.plan({...M.example,capacityPerFte:.001,unitsConfirmed:true,unitReviewReason:'Synthetic unit-confirmation boundary exercise'});assert.equal(reviewed.review.required,true);assert.equal(reviewed.scenarios.base.final.annualGapCost,127272*300000);});
test('unstarted hires are reviewed before existing staff; rounded deferral cannot create a shortage',()=>{const v=M.plan({...M.example,committedHires:6});assert.equal(v.actions[0].type,'defer-hires');assert.equal(v.actions[0].quantity,5);assert.equal(v.actions.some(a=>a.type==='move'),false);assert.ok(v.scenarios.base.final.rawForecastSupplyFte-5>=v.scenarios.base.final.rawRequiredFte);const mixed=M.plan({...M.example,targetWorkload:50,committedHires:2});assert.equal(mixed.actions[0].type,'defer-hires');assert.equal(mixed.actions[1].type,'move');});
test('annual incumbent attrition supports 60–100 percent without silently capping at 80',()=>{for(const rate of [60,90,100]){const v=M.plan({...M.example,horizonYears:1,attritionPercent:rate,productivityGainPercent:0});assert.equal(v.scenarios.base.assumptions.annualAttritionPercent,rate);assert.ok(Math.abs(v.scenarios.base.final.rawForecastSupplyFte-2*(1-rate/100))<1e-9);}assert.throws(()=>M.plan({...M.example,attritionPercent:120}),/Attrition/);});
test('actual incumbents are aggregated individually and CSV round-trip preserves data',()=>{
 const csv='id,currentSalary,progressionEligible,progressionEvidence\nP001,23000,false,\nP002,25000,false,\nP003,39000,false,';
 const v=C.evaluate({...C.example,headcount:99,rosterCsv:csv,oncostPercent:0});assert.equal(v.input.headcount,3);assert.equal(v.result.annualBasePayroll,(24000+25000+39000)*12);assert.equal(v.result.annualAdjustmentCost,12000);assert.equal(v.result.recommendedSalary,null);assert.equal(v.incumbents[2].result.payAction,'red-circle');const imported=C.evaluate(v.input);assert.equal(imported.result.annualEmployerCost,v.result.annualEmployerCost);
 assert.throws(()=>C.evaluate({...C.example,rosterCsv:'id,currentSalary\nP1,\nP2,20000'}),/actual salary/);assert.throws(()=>C.evaluate({...C.example,rosterCsv:'id,currentSalary\nP1,23000\nP1,24000'}),/unique/);assert.throws(()=>C.parseRoster('name,salary\nAli,20000'),/template headers/);
});
const saudi={mode:'saudi',asOf:'2026-10-05',regime:'saudi-new',applicabilityConfirmed:true,sanedEligible:true,housingMonthly:2500,otherMonthly:500,contributoryExtraMonthly:0,medicalAnnual:4000,serviceYears:4.5};
test('Saudi breakdown applies the dated regime, ceiling, fixed medical cost and service-year crossover',()=>{
 const b=C.saudiCost(10000,'monthly',saudi);assert.equal(b.employerRatePercent,12.75);assert.equal(b.contributoryWage,12500);assert.equal(b.annualGosi,19125);assert.equal(b.annualEosServiceAccrual,9750);assert.equal(b.medicalAnnual,4000);assert.equal(b.annualEmployerCost,188875);
 assert.equal(C.saudiCost(10000,'monthly',{...saudi,asOf:'2025-07-01'}).pensionRate,9.5);assert.equal(C.saudiCost(10000,'monthly',{...saudi,regime:'saudi-existing'}).employerRatePercent,11.75);assert.equal(C.saudiCost(50000,'monthly',{...saudi,regime:'non-saudi'}).annualGosi,10800);
 assert.throws(()=>C.saudiCost(10000,'monthly',{...saudi,regime:'gcc'}),/specialist/);assert.throws(()=>C.saudiCost(10000,'monthly',{...saudi,asOf:'2029-01-01'}),/source review/);assert.throws(()=>C.evaluate({...C.example,employerCosts:saudi}),/double counting/);
});
test('eight-factor illustrative grading spans the attainable 0–1000 range over 12 contiguous grades',()=>{
 const ctx=vm.createContext({window:{},localStorage:{}});vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/enterprise-core.js'),'utf8'),ctx);const grade=ctx.window.MiyarEnterpriseCore.customGrade;
 assert.equal(F.factors.length,8);assert.equal(F.bands.length,12);assert.equal(F.factors.reduce((a,f)=>a+f.weight,0),100);assert.equal(grade(F,Object.fromEntries(F.factors.map(f=>[f.id,'1']))).points,0);assert.equal(grade(F,Object.fromEntries(F.factors.map(f=>[f.id,'6']))).points,1000);for(let i=1;i<F.bands.length;i++)assert.equal(F.bands[i].min,F.bands[i-1].max+1);assert.equal(F.illustrative,true);assert.match(F.notice,/incumbent performance/);
});
test('source update preview verifies actual source bytes, detects impacted codes and never activates',()=>{
 const bytes=Buffer.from('Synthetic source, not a real classification release'),base={id:'old',fields:[{code:'041101',titleAr:'محاسبة',sourcePage:1}]},candidate={id:'new',schema:'miyar-education/1.0',edition:'test',sha256:crypto.createHash('sha256').update(bytes).digest('hex'),fields:[{code:'041101',titleAr:'محاسبة محدثة',sourcePage:1}]},record={sourceUrl:'https://www.moe.gov.sa/example',sourceReviewed:true,reviewedBy:'Test reviewer',reviewedOn:'2026-10-05',reason:'Synthetic review test'};
 const r=review('education',base,candidate,bytes,record,[{id:'P1',content:{educationFieldCode:'041101'}}]);assert.deepEqual(r.changed,['041101']);assert.deepEqual(r.affectedPositionIds,['P1']);assert.equal(r.activationAllowed,false);assert.throws(()=>review('education',base,candidate,Buffer.from('changed'),record),/SHA256/);
});
test('authored fixtures and passing code tests cannot satisfy the independent commercial gate',()=>{const r=assess(require('../docs/expert-review/launch-readiness.json'));assert.equal(r.commercialReady,false);assert.ok(r.blockers.some(x=>x.includes('Saudi')));assert.ok(r.blockers.some(x=>x.includes('Independent')));assert.equal(cases.status,'not-an-independent-golden-set');assert.equal(cases.cases.length,40);});
test('commercial launch CLI reports blockers with the flag alone or an explicit manifest',()=>{for(const args of [['--require-commercial'],['docs/expert-review/launch-readiness.json','--require-commercial']]){const r=require('node:child_process').spawnSync(process.execPath,['scripts/check-professional-readiness.cjs',...args],{cwd:path.join(__dirname,'..'),encoding:'utf8'});assert.equal(r.status,1);assert.equal(JSON.parse(r.stdout).commercialReady,false);assert.equal(r.stderr,'');}});
