const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM,VirtualConsole}=require('jsdom');
const dist=path.join(__dirname,'../dist'),tick=()=>new Promise(r=>setTimeout(r,35));
async function boot(options={}){const errors=[],v=new VirtualConsole();v.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(fs.readFileSync(path.join(dist,'index.html'),'utf8'),{url:'https://example.test/#demo',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:v}),w=dom.window;
 w.localStorage.setItem('miyar-language','en');w.structuredClone=structuredClone;w.AbortSignal=AbortSignal;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.confirm=()=>true;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 w.fetch=async url=>{const name=String(url);if(name.startsWith('./')){if(options.beforeFetch)await options.beforeFetch(name);return {ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(dist,name.split('?')[0]),'utf8'))};}if(options.remoteFetch)return options.remoteFetch(name);return {ok:true,json:async()=>({})};};
 for(const s of w.document.querySelectorAll('script[src]'))w.eval(fs.readFileSync(path.join(dist,s.getAttribute('src').split('?')[0]),'utf8'));await tick();return {w,dom,errors};}
function run(w,objective,domain='الموارد البشرية',seniority='أخصائي'){for(const [id,value] of Object.entries({objective,domain,seniority})){const el=w.document.getElementById(id);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));}w.document.getElementById('role-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}
test('real script order returns one validated specialist card and carries it into OD',async()=>{const a=await boot();try{run(a.w,'اعداد ومعالجة الرواتب شهريا وارفع تقارير للمدير المالي');await tick();const d=a.w.document;assert.equal(d.querySelectorAll('.demo-v5-directory').length,1);assert.equal(d.querySelector('.demo-v5-primary-recommendation > h4').textContent,'Payroll Specialist');assert.equal(d.querySelectorAll('.demo-validation li').length,5);assert.match(d.querySelector('.demo-final-title').textContent,/Payroll Specialist/);assert.equal(d.querySelector('[data-demo-ref] strong').textContent,'242322');d.querySelector('[data-demo-primary-hr]').click();await new Promise(r=>setTimeout(r,750));assert.equal(d.querySelector('[data-field=title]').value,'Payroll Specialist');assert.equal(d.querySelector('[data-field=occupationCode]').value,'242322');assert.deepEqual(a.errors,[]);}finally{a.dom.window.close();}});
test('directory outage has a retry state and retry resolves without duplicate fallbacks',async()=>{let fail=true;const a=await boot({beforeFetch:async name=>{if(fail&&name.includes('ssco-2019'))throw Error('offline');}});try{run(a.w,'payroll processing');await tick();assert.match(a.w.document.getElementById('result-content').textContent,/directory unavailable/);fail=false;a.w.document.querySelector('[data-demo-retry]').click();await tick();assert.equal(a.w.document.querySelectorAll('.demo-v5-directory').length,1);assert.match(a.w.document.querySelector('.demo-final-title').textContent,/Payroll Specialist/);}finally{a.dom.window.close();}});
test('in-flight old results cannot overwrite edited input or a newer run',async()=>{let release;const pending=new Promise(r=>release=r);const a=await boot({beforeFetch:async name=>{if(name.includes('ssco-2019'))await pending;}});try{run(a.w,'payroll');run(a.w,'إدارة حملات التسويق الرقمي','التسويق');release();await tick();assert.equal(a.w.document.querySelectorAll('.demo-v5-directory').length,1);assert.match(a.w.document.querySelector('.demo-final-title').textContent,/Digital Marketing/);assert.doesNotMatch(a.w.document.querySelector('.demo-v5-output').textContent,/Payroll Specialist/);}finally{release();a.dom.window.close();}});
test('finance payroll cost conflict is visible and can switch the selected domain',async()=>{const a=await boot();try{run(a.w,'تحليل تكلفة الرواتب ضمن الميزانية','المالية');await tick();assert.match(a.w.document.querySelector('.demo-final-title').textContent,/Cost Accountant/);assert.ok(a.w.document.querySelector('.demo-domain-conflict'));a.w.document.querySelector('[data-demo-switch]').click();await tick();assert.match(a.w.document.querySelector('.demo-final-title').textContent,/Payroll Specialist/);}finally{a.dom.window.close();}});
test('OD specialist subroles have relevant metrics without inherited procurement skills',async()=>{const a=await boot();try{for(const [objective,metric] of [['توظيف واستقطاب المرشحين','time to fill'],['إعداد الرواتب','correct payroll'],['تخطيط القوى العاملة','forecast demand']]){const p=a.w.MiyarODEngine.generate({strategyObjective:objective,department:'الموارد البشرية',requestedLevel:'أخصائي',responsibilities:objective+'\nتوثيق نتائج العمل\nمتابعة جودة التنفيذ'},'en');assert.doesNotMatch(p.content.skills,/procurement|OPEX/i);assert.match(p.content.kpis.map(x=>x.metric).join(' '),new RegExp(metric));assert.match(p.content.careerPath,/Senior .* Specialist → Manager/);assert.equal(p.gradeRecommendation.level,'specialist');}}finally{a.dom.window.close();}});
function chooseAI(w){const mode=w.document.querySelector('#demo-engine-mode');mode.value='ai';mode.dispatchEvent(new w.Event('change',{bubbles:true}));}
test('original AI mode explicitly reports unavailable instead of substituting a rules result',async()=>{for(const response of [{ok:false,status:404},{ok:true,json:async()=>({configured:false})}]){const a=await boot({remoteFetch:async()=>response});try{chooseAI(a.w);run(a.w,'payroll processing');await tick();const d=a.w.document;assert.match(d.querySelector('#result-content').textContent,/AI pipeline did not complete/);assert.equal(d.querySelectorAll('.demo-v5-directory').length,0);assert.equal(d.querySelectorAll('.demo-final-title').length,0);assert.equal(d.querySelector('.demo-ai-notice').hidden,false);}finally{a.dom.window.close();}}});
test('configured original AI requires consent before submitting and displays actual pipeline result',async()=>{const a=await boot({remoteFetch:async()=>({ok:true,json:async()=>({configured:true})})});try{let calls=0;chooseAI(a.w);a.w.MiyarEnterprise.session=()=>({userId:'test'});a.w.MiyarEnterprise.analyzeStrategic=async body=>{calls++;assert.equal(body.consentExternalProcessing,true);assert.equal(body.text,'payroll processing');return {route:'generated-proposal',cosineSimilarity:.25,validation:{rationale:'Validated against objective'},finalTitle:'Payroll Innovation Specialist',occupationCode:null,finalRationale:'New proposal for review'};};run(a.w,'payroll processing');await tick();assert.equal(calls,0);assert.match(a.w.document.querySelector('#result-content [role=alert]').textContent,/accept the AI data-processing notice/);a.w.document.querySelector('#demo-ai-consent').checked=true;run(a.w,'payroll processing');await tick();assert.equal(calls,1);assert.match(a.w.document.querySelector('.demo-final-title').textContent,/Payroll Innovation Specialist/);assert.match(a.w.document.querySelector('#result-content').textContent,/Unmapped/);}finally{a.dom.window.close();}});
