const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const M=require('../dist/manpower-engine.js'),dir=path.join(__dirname,'../dist');
const baseline={...M.example,voluntaryAttritionPercent:5,involuntaryAttritionPercent:0,newHireAttritionPercent:0,hireLeadDays:0};
test('compound incumbent attrition and all workforce presentations share two-decimal supply',()=>{
 const p=M.plan(baseline);assert.equal(p.scenarios.base.final.forecastSupplyFte,1.71);assert.equal(p.bridge.forecastSupplyFte,1.71);assert.equal(p.scenarios.base.final.gapFte,.83);
 const compound=M.plan({...baseline,voluntaryAttritionPercent:10,involuntaryAttritionPercent:20});assert.ok(Math.abs(compound.input.attritionRate-.28)<1e-12);assert.equal(compound.scenarios.base.final.forecastSupplyFte,.75);
 for(const s of Object.values(compound.scenarios))assert.ok(Math.abs(s.final.forecastSupplyFte-(compound.input.currentFte*(.72**3)))<.005);
});
test('hiring lead days reduce effective supply and gaps use that delayed capacity',()=>{
 const instant=M.plan({...baseline,horizonYears:1,committedHires:2}),delayed=M.plan({...baseline,horizonYears:1,committedHires:2,hireLeadDays:120});
 assert.equal(instant.scenarios.base.final.effectiveHiredFte,2);assert.equal(delayed.scenarios.base.final.effectiveHiredFte,1.34);assert.equal(delayed.scenarios.base.final.hiredStockAtYearEndFte,2);
 assert.ok(delayed.scenarios.base.final.rawGapFte>instant.scenarios.base.final.rawGapFte);assert.ok(delayed.scenarios.base.final.hiringDelayCapacityLossFte>0);
 const afterHorizon=M.plan({...baseline,horizonYears:1,committedHires:2,hireLeadDays:400});assert.equal(afterHorizon.scenarios.base.final.effectiveHiredFte,0);assert.equal(afterHorizon.scenarios.base.final.hiredStockAtYearEndFte,0);
});
test('new-hire attrition reduces pipeline separately from incumbent voluntary and involuntary attrition',()=>{
 const absent=M.plan({...baseline,currentFte:0,committedHires:2,horizonYears:1}),firstYear=M.plan({...baseline,currentFte:0,committedHires:2,horizonYears:1,newHireAttritionPercent:25});
 assert.equal(absent.scenarios.base.final.forecastSupplyFte,2);assert.equal(firstYear.scenarios.base.final.forecastSupplyFte,1.5);assert.equal(firstYear.scenarios.base.final.attritionExitsFte,0);
 assert.throws(()=>M.plan({...baseline,involuntaryAttritionPercent:101}),/Involuntary attrition/);assert.throws(()=>M.plan({...baseline,newHireAttritionPercent:''}),/New-hire attrition/);assert.throws(()=>M.plan({...baseline,hireLeadDays:90.5}),/Hiring lead days/);
});
const cost={positionId:'P-MP',revision:2,role:'Operational analyst',grade:'G07',currency:'SAR',annualEmployerCostPerFte:194125,scope:'guest',calculatedAt:'2026-10-05T12:00:00Z',bandSource:'Approved organization band',source:'compensation-calculation'};
test('annual whole-hire budget uses matching compensation employer cost, not salary midpoint',()=>{
 const p=M.plan({...baseline,positionId:'P-MP',positionRevision:2,grade:'G07',costContext:cost,annualCostPerFte:194125});assert.equal(p.scenarios.base.final.annualGapCost,194125);assert.equal(p.input.costContext.source,'compensation-calculation');
 assert.equal(p.scenarios.base.final.annualFractionalCapacityCost,161261);
 for(const patch of [{positionId:'OTHER'},{positionRevision:3},{grade:'G08'},{annualCostPerFte:194124},{costContext:{...cost,currency:'USD'}}])assert.throws(()=>M.plan({...baseline,positionId:'P-MP',positionRevision:2,grade:'G07',annualCostPerFte:194125,costContext:cost,...patch}),/Compensation cost must match/);
});
async function ui({rows=[],context=null,selected=null,reviewed=true,locale='en'}={}){
 const dom=new JSDOM('<!doctype html><html lang="'+locale+'"><body><h1 id="enterprise-heading"></h1><span id="breadcrumb-title"></span><div class="sidebar"><nav class="nav-list"><a data-enterprise-open="create"></a></nav></div><main id="ent-content"></main></body></html>',{url:'https://example.test/Miyar/#enterprise/manpower',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.HTMLElement.prototype.scrollIntoView=()=>{};w.MiyarEnterprise={session:()=>null,positionRegistry:async()=>rows,positionContext:()=>selected};w.MiyarCompensationWorkbench={getCostContext:()=>context};w.MiyarEnterpriseGrade={contextFor:p=>reviewed?{...p.content,salaryGrade:p.content?.grade||p.content?.salaryGrade||'',evaluatedPositionId:p.id,evaluatedPositionRevision:p.revision}:null};for(const f of ['scenario-workspace.js','manpower-engine.js','manpower-workbench.js'])w.eval(fs.readFileSync(path.join(dir,f),'utf8'));await new Promise(r=>setTimeout(r,20));return {w,d:w.document,close:()=>w.close(),$:id=>w.document.getElementById('mp-'+id)};
}
test('workforce example fields round high-demand percentage and UI discloses operational suitability',async()=>{const a=await ui();try{a.d.querySelector('[data-mp-example]').click();assert.equal(a.$('high-demand').value,'110');assert.match(a.d.querySelector('.mp-model-notice').textContent,/Knowledge and supervisory roles need separate/);a.d.querySelector('[data-mp-run]').click();assert.equal(a.d.querySelectorAll('.mp-scenario').length,3);assert.match(a.d.querySelector('.mp-bridge').textContent,/1\.71/);assert.match(a.d.querySelector('.mp-scenario.good,.mp-scenario.warn').textContent,/1\.71/);assert.equal(a.d.activeElement.className,'mp-results');assert.deepEqual([...a.d.querySelectorAll('.mp-table-wrap tbody tr')].map(r=>r.cells[4].textContent),['1.9','1.8','1.71']);}finally{a.close();}});
test('position import binds revision and grade, brings occupied/vacant counts and matching employer cost',async()=>{const a=await ui({rows:[{id:'P-MP',revision:2,title:'Operational analyst',state:'active',content:{grade:'G07',headcount:3,occupiedFte:2,vacantFte:1,jobFamily:'Finance'}}],context:cost});try{a.d.querySelector('[data-mp-example]').click();a.$('position').value='P-MP';a.d.querySelector('[data-mp-import-position]').click();assert.equal(a.$('revision').value,'2');assert.equal(a.$('grade').value,'G07');assert.equal(a.$('current').value,'2');assert.equal(a.$('vacant').value,'1');assert.equal(a.$('cost').value,'194125');assert.match(a.d.querySelector('[data-mp-cost-note]').textContent,/matching the position, revision and grade/);a.d.querySelector('[data-mp-run]').click();assert.equal(a.w.MiyarManpowerWorkbench.getResult().input.costContext.positionId,'P-MP');assert.match(a.d.querySelector('.mp-results').textContent,/P-MP · v2 · G07/);}finally{a.close();}});
test('unrelated compensation result is never imported and unknown occupied count is not inferred',async()=>{const a=await ui({rows:[{id:'P-MP',revision:3,title:'Operational analyst',state:'active',content:{grade:'G07',headcount:20}}],context:cost});try{a.d.querySelector('[data-mp-example]').click();a.$('position').value='P-MP';a.d.querySelector('[data-mp-import-position]').click();assert.equal(a.$('current').value,'');assert.equal(a.$('vacant').value,'');assert.equal(a.$('cost').value,'');a.d.querySelector('[data-mp-run]').click();assert.equal(a.$('current').getAttribute('aria-invalid'),'true');assert.equal(a.d.activeElement,a.$('current'));assert.match(a.$('current').getAttribute('aria-describedby'),/mp-input-error/);assert.equal(a.d.querySelector('[data-mp-message]').closest('.mp-run').querySelector('[data-mp-run]')!==null,true);}finally{a.close();}});
test('blank required attrition fields focus the exact invalid field with Arabic feedback beside action',async()=>{const a=await ui({locale:'ar'});try{a.d.querySelector('[data-mp-example]').click();a.$('new-attrition').value='';a.d.querySelector('[data-mp-run]').click();assert.equal(a.d.activeElement,a.$('new-attrition'));assert.equal(a.$('new-attrition').getAttribute('aria-invalid'),'true');assert.equal(a.d.querySelector('[data-mp-planning-options]').open,true);assert.match(a.d.querySelector('[data-mp-message]').textContent,/راجع القيمة/);assert.equal(a.d.querySelectorAll('.mp-results').length,0);}finally{a.close();}});

test('progressive manpower form begins with core inputs and purpose hints explain the decision effect',async()=>{const a=await ui();try{assert.equal(a.d.querySelector('[data-mp-planning-options]').open,false);assert.equal(a.d.querySelector('[data-mp-context-options]').open,false);const visible=[...a.d.querySelectorAll('.mp-field input,.mp-field textarea,.mp-field select')].filter(el=>!closed(el));function closed(el){for(let p=el.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS'&&!p.open)return true;return false;}assert.ok(visible.length<=8,visible.length);for(const id of ['current','vacant','baseline','target','capacity','hire-days','attrition','productivity','cost'])assert.ok(a.$(id+'-hint')?.textContent.length>60,id);assert.match(a.$('current-hint').textContent,/so you do not hire/);assert.match(a.$('cost-hint').textContent,/including employer obligations/);}finally{a.close();}});
test('verified selected position prefills its revision and matching cost, while unknown draft occupancy stays blank',async()=>{const a=await ui({rows:[{id:'P-MP',revision:2,title:'Operational analyst',state:'draft',content:{grade:'G07',headcount:20,jobFamily:'Finance'}}],selected:{id:'P-MP',revision:2},context:cost});try{assert.equal(a.$('position').value,'P-MP');assert.equal(a.$('role').value,'Operational analyst');assert.equal(a.$('revision').value,'2');assert.equal(a.$('grade').value,'G07');assert.equal(a.$('cost').value,'194125');assert.equal(a.$('current').value,'');assert.equal(a.$('vacant').value,'');assert.match(a.d.querySelector('[data-mp-context-note]').textContent,/Suggested prefill from the position registry: Operational analyst · v2 · P-MP · G07/);assert.match(a.d.querySelector('[data-mp-context-note]').textContent,/Occupied count is undocumented/);assert.match(a.d.querySelector('[data-mp-cost-note]').textContent,/2026-10-05/);}finally{a.close();}});
test('selected position with a stale revision does not silently prefill from another revision',async()=>{const a=await ui({rows:[{id:'P-MP',revision:3,title:'Operational analyst',state:'active',content:{grade:'G07',occupiedFte:2,vacantFte:1}}],selected:{id:'P-MP',revision:2},context:cost});try{assert.equal(a.$('position').value,'');assert.equal(a.$('role').value,'');assert.equal(a.$('grade').value,'');assert.equal(a.$('cost').value,'');}finally{a.close();}});

test('same-position rerenders and language changes preserve unsaved actual-count edits',async()=>{const a=await ui({rows:[{id:'P-MP',revision:2,title:'Operational analyst',state:'active',content:{grade:'G07',occupiedFte:2,vacantFte:1,jobFamily:'Finance'}}],selected:{id:'P-MP',revision:2},context:cost});try{a.$('current').value='3.5';a.$('current').dispatchEvent(new a.w.Event('input',{bubbles:true}));a.$('target').value='240';a.$('target').dispatchEvent(new a.w.Event('input',{bubbles:true}));a.w.MiyarManpowerWorkbench.render();await new Promise(r=>setTimeout(r,20));assert.equal(a.$('current').value,'3.5');assert.equal(a.$('target').value,'240');assert.equal(a.$('cost').value,'194125');a.d.documentElement.lang='ar';a.w.MiyarManpowerWorkbench.render();await new Promise(r=>setTimeout(r,20));assert.equal(a.$('current').value,'3.5');assert.equal(a.$('target').value,'240');assert.equal(a.$('position').value,'P-MP');assert.equal(a.$('revision').value,'2');}finally{a.close();}});
test('an explicit manual scenario stays manual across rerenders even when a selected registry position exists',async()=>{const a=await ui({rows:[{id:'P-MP',revision:2,title:'Operational analyst',state:'active',content:{grade:'G07',occupiedFte:2,vacantFte:1}}],selected:{id:'P-MP',revision:2},context:cost});try{a.$('position').value='';a.$('position').dispatchEvent(new a.w.Event('change',{bubbles:true}));assert.equal(a.$('role').readOnly,false);assert.equal(a.$('grade').readOnly,false);assert.equal(a.$('current').value,'');assert.equal(a.$('cost').value,'');a.w.MiyarManpowerWorkbench.render();await new Promise(r=>setTimeout(r,20));assert.equal(a.$('position').value,'');assert.equal(a.$('current').value,'');assert.equal(a.$('role').value,'');}finally{a.close();}});

test('raw remote salary-grade identity claims are not authoritative when context verification fails',async()=>{const a=await ui({reviewed:false,rows:[{id:'P-MP',revision:2,title:'Operational analyst',state:'active',content:{salaryGrade:'G07',grade:'G07',evaluatedPositionId:'P-MP',evaluatedPositionRevision:2,occupiedFte:2,vacantFte:1}}],selected:{id:'P-MP',revision:2},context:cost});try{assert.equal(a.$('role').value,'Operational analyst');assert.equal(a.$('grade').value,'');assert.equal(a.$('cost').value,'');assert.match(a.d.querySelector('[data-mp-context-note]').textContent,/no approved evaluation/);}finally{a.close();}});
test('a local grade annotation stays an explicit proposal and is never described as server approval',async()=>{const a=await ui({reviewed:false,rows:[{id:'LOCAL-MP',revision:2,title:'Operational analyst',state:'draft',content:{salaryGrade:'G07',evaluatedPositionId:'LOCAL-MP',evaluatedPositionRevision:2}}],selected:{id:'LOCAL-MP',revision:2}});try{assert.equal(a.$('grade').value,'G07');assert.match(a.d.querySelector('[data-mp-context-note]').textContent,/local review proposal, not server approval/);assert.equal(a.$('current').value,'');}finally{a.close();}});
test('matching compensation events preserve manual cost, while explicit sourced import can be undone',async()=>{const a=await ui({rows:[{id:'P-MP',revision:2,title:'Operational analyst',state:'active',content:{grade:'G07',occupiedFte:2,vacantFte:1}}],selected:{id:'P-MP',revision:2},context:cost});try{a.$('cost').value='123456';a.$('cost').dispatchEvent(new a.w.Event('input',{bubbles:true}));a.w.dispatchEvent(new a.w.CustomEvent('miyar:compensation-cost-context',{detail:{...cost,annualEmployerCostPerFte:200000}}));assert.equal(a.$('cost').value,'123456');a.d.querySelector('[data-mp-import-cost]').click();assert.equal(a.$('cost').value,'194125');assert.match(a.d.querySelector('[data-mp-cost-note]').textContent,/compensation result matching/);a.d.querySelector('[data-mp-undo-cost]').click();assert.equal(a.$('cost').value,'123456');assert.match(a.d.querySelector('[data-mp-cost-note]').textContent,/Manually entered/);}finally{a.close();}});

test('invalid high-scenario controls focus the exact high field and open its closed section',async()=>{for(const [id,value]of [['high-demand','900'],['high-productivity','201'],['high-attrition','51']]){const a=await ui();try{a.d.querySelector('[data-mp-example]').click();a.$(id).value=value;assert.equal(a.$(id).closest('details').open,false);a.d.querySelector('[data-mp-run]').click();assert.equal(a.d.activeElement,a.$(id),id);assert.equal(a.$(id).getAttribute('aria-invalid'),'true');assert.equal(a.$(id).closest('details').open,true);assert.equal(a.$('low-'+id.split('-')[1]).getAttribute('aria-invalid'),null);}finally{a.close();}}});

test('global compensation invalidation clears sourced manpower cost and its provenance, preserving manual values',async()=>{const options={rows:[{id:'P-MP',revision:2,title:'Operational analyst',state:'active',content:{grade:'G07',occupiedFte:2,vacantFte:1}}],selected:{id:'P-MP',revision:2},context:cost};const a=await ui(options);try{assert.equal(a.$('cost').value,'194125');a.w.dispatchEvent(new a.w.CustomEvent('miyar:compensation-cost-context',{detail:null}));assert.equal(a.$('cost').value,'');assert.doesNotMatch(a.d.querySelector('[data-mp-cost-note]').textContent,/compensation result matching/);a.w.MiyarManpowerWorkbench.render();await new Promise(r=>setTimeout(r,20));assert.equal(a.$('cost').value,'');a.$('cost').value='123456';a.$('cost').dispatchEvent(new a.w.Event('input',{bubbles:true}));a.w.dispatchEvent(new a.w.CustomEvent('miyar:compensation-cost-context',{detail:null}));assert.equal(a.$('cost').value,'123456');assert.match(a.d.querySelector('[data-mp-cost-note]').textContent,/Manually entered/);}finally{a.close();}});
test('compensation invalidation while manpower is unmounted removes stale sourced cost on return without losing numeric edits',async()=>{const a=await ui({rows:[{id:'P-MP',revision:2,title:'Operational analyst',state:'active',content:{grade:'G07',occupiedFte:2,vacantFte:1}}],selected:{id:'P-MP',revision:2},context:cost});try{a.$('target').value='240';a.$('target').dispatchEvent(new a.w.Event('input',{bubbles:true}));a.d.querySelector('#ent-content').replaceChildren();a.w.dispatchEvent(new a.w.CustomEvent('miyar:compensation-cost-context',{detail:null}));a.w.MiyarManpowerWorkbench.render();await new Promise(r=>setTimeout(r,20));assert.equal(a.$('cost').value,'');assert.equal(a.$('target').value,'240');assert.equal(a.$('current').value,'2');}finally{a.close();}});
