'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),R=require('../dist/role-recommender.js');
const nodes=require('../dist/classifications/ssco-2019.json').nodes,education=require('../dist/classifications/education-2020.json').fields;
const propose=input=>R.recommend(input,nodes,education);
// Additional authored counterexamples. They are not the independent golden set.
for(const [text,count,want]of [
 ['Oversee a group of 7 auditors and sign off internal audit plans',7,'manager'],
 ['Manage a unit of 18 analysts; approve financial statements',18,'director'],
 ['قيادة وحدة من ٧ محاسبين؛ اعتماد إقفال الحسابات',7,'manager'],
 ['يدير قسمًا من ١٨ محاسبًا؛ يعتمد القوائم المالية',18,'director']
])test('general people evidence: '+text,()=>{const r=R.analyzeLevel({responsibilities:text});assert.equal(r.level,want);assert.equal(r.directReports,count);assert.ok(r.evidence.people.length);assert.ok(r.evidence.approval.length);});
for(const [title,want]of [['Head of Compliance','director'],['Director of Human Resources','director'],['مدير إدارة المالية','director'],['مدير الموارد البشرية','manager']])test('own title retains hierarchy: '+title,()=>assert.equal(R.level({title}),want));
for(const text of ['Prepare accounting entries and report findings to the Chief Executive','إعداد القيود المحاسبية ورفع التقارير للرئيس التنفيذي','Review investment opportunities without leading a team of 22 analysts'])test('recipient/excluded titles do not confer rank: '+text,()=>{const r=R.analyzeLevel({responsibilities:text});assert.equal(r.level,'specialist');assert.equal(r.directReports,null);});
test('explicit specialist cannot publish a role with conflicting people-and-approval evidence',()=>{const r=propose({department:'Finance',seniority:'specialist',responsibilities:'Manage a team of 9 accountants; approve accounting entries; review bank reconciliations'});assert.equal(r.status,'blocked');assert.equal(r.finalTitle,null);assert.equal(r.levelAnalysis.leadershipConflict,true);});
test('two meaningful clauses do not require newlines',()=>{const r=propose({department:'Internal Audit',responsibilities:'Test controls and document audit evidence and monitor audit findings'});assert.equal(r.candidate.family,'internalAudit');assert.ok(r.detection.evidence.specialtyClauses>=2);});
test('one repeated specialized clause cannot manufacture two duties',()=>{const input={department:'Finance',responsibilities:'Prepare accounting entries; prepare accounting entries; prepare a report'};assert.equal(propose(input).status,'needs-confirmation');assert.equal(propose(input).finalTitle,null);});
test('shared commercial words do not select a specialty even with Finance selected',()=>{const input={department:'Finance',responsibilities:'Review cost reports; update budget reports; prepare reports'};assert.equal(propose(input).status,'needs-confirmation');assert.equal(propose(input).finalTitle,null);});
test('routine payable records retain a clerk and relevant metrics',()=>{const r=propose({department:'Finance',responsibilities:'Enter vendor invoices; match supplier invoices; archive invoice evidence'});assert.equal(r.candidate.level,'assistant');assert.match(r.candidate.titleEn,/Clerk/);assert.doesNotMatch(r.candidate.titleEn,/Analyst|Manager/);assert.match(r.candidate.metricEn,/invoices/i);});
for(const [department,responsibilities]of [
 ['Security','Conduct security patrols; verify visitor access; document access control exceptions'],
 ['الأمن والسلامة','تنفيذ جولات أمنية؛ فحص معدات الوقاية؛ تنسيق الإخلاء']
])test('security and safety retain licensing review: '+department,()=>{const r=propose({department,responsibilities});assert.equal(r.candidate.family,'securitySafety');assert.equal(r.checks.find(x=>x.id==='license').status,'warn');assert.match(r.candidate.skillsEn.join(' '),/Access|hazard|Safety/i);});
test('physical repair work never receives an engineer title from an explicit specialist request',()=>{const r=propose({department:'Maintenance',requestedLevel:'specialist',responsibilities:'Inspect HVAC preventive maintenance; repair electrical faults; document work orders'});assert.equal(r.candidate.level,'technician');assert.doesNotMatch(r.candidate.titleEn,/Engineer/);});
test('all added occupational links point to real supplied codes and pages',()=>{for(const r of R.catalog.roles){const source=nodes.find(x=>x.level==='occupation'&&x.code===r.ssco);assert.ok(source,r.titleEn);assert.equal(source.sourcePage,r.sourcePage,r.titleEn);for(const code of r.educationCodes)assert.ok(education.some(x=>x.code===code),r.titleEn+' '+code);}});
test('an independently owned leadership duty after a recipient survives context removal',()=>{const r=propose({department:'Finance',responsibilities:'Report findings to the Finance Director and supervise a team of 8 accountants and approve accounting entries and review bank reconciliations'});assert.equal(r.candidate.level,'manager');assert.equal(r.directReports,8);assert.doesNotMatch(r.detection.text,/Finance Director/);assert.match(r.detection.text,/supervise a team/);});
test('cybersecurity tasks do not acquire physical-security licensing scope',()=>{const r=propose({department:'Information Technology',responsibilities:'Monitor cyber security controls; assess information security risk'});assert.equal(r.candidate.family,'it');assert.equal(r.detection.workstreams.some(x=>x.family.id==='securitySafety'),false);assert.equal(r.checks.some(x=>x.id==='license'),false);});
test('a no-management constraint cannot silently erase explicitly owned people leadership',()=>{const r=propose({department:'Finance',constraints:'no management duties',responsibilities:'Lead a team of 8 accountants; approve accounting entries; review bank reconciliations'});assert.equal(r.status,'blocked');assert.equal(r.finalTitle,null);assert.equal(r.checks.find(x=>x.id==='leadership').status,'fail');});
for(const [locale,department,objective,title,duties]of [
 ['ar','المالية','ضبط إقفال الحسابات المالية','مدير إدارة المالية','إعطاء الأدوية، مراقبة العلامات الحيوية، توثيق خطط الرعاية'],
 ['en','Finance','Prepare financial statements and reconcile bank accounts','Finance Director','Administer medications; monitor vital signs; document nursing care plans'],
 ['ar','التسويق','تخطيط حملات التسويق وتحليل عائد الحملات','مدير التسويق','تسجيل القيود المحاسبية؛ تسوية الحسابات البنكية؛ إقفال الحسابات'],
 ['en','Procurement','Evaluate supplier bids and source purchase orders','Procurement Manager','Train machine learning models; engineer data features; evaluate model accuracy']
])test('a department-aligned objective/title cannot disguise contradictory duties '+locale+' '+department,()=>{const input={department,strategyObjective:objective,title,responsibilities:duties,locale};const d=R.detect(input);assert.equal(d.severeConflict,true);assert.equal(d.evidenceSource,'responsibilities');assert.equal(d.evidence.fieldTaskScore,0);assert.ok(d.contextInterpretation.raw.includes(objective));assert.doesNotMatch(d.text,new RegExp(locale==='ar'?'ضبط إقفال|تخطيط حملات':'Prepare financial|Evaluate supplier'));assert.throws(()=>propose(input),e=>e.code==='MIYAR_DOMAIN_CONFLICT');assert.throws(()=>R.validateScope(input,locale),e=>e.code==='MIYAR_DOMAIN_CONFLICT');});
for(const input of [
 {department:'Finance',strategyObjective:'Reconcile bank accounts and prepare financial statements',title:'Accountant',responsibilities:'Prepare cost reports; monitor budget reports'},
 {department:'Finance',strategyObjective:'Reconcile bank accounts and prepare financial statements',title:'Accountant',responsibilities:'Prepare accounting entries; prepare accounting entries; prepare a monthly report'},
 {department:'Human Resources',strategyObjective:'Process payroll and reconcile GOSI contributions',title:'Payroll Specialist',responsibilities:'Help with everything; prepare reports'}
])test('objective/title cannot supply missing specialized duty evidence '+input.responsibilities,()=>{if(R.detect(input)?.fieldFamily){assert.equal(propose(input).status,'needs-confirmation');assert.equal(propose(input).finalTitle,null);}else{assert.equal(propose(input),null);assert.throws(()=>R.validateScope(input),e=>e.code==='MIYAR_UNSUPPORTED_SCOPE');}});
for(const [department,objective,conflict]of [
 ['Human Resources','Improve financial controls, consolidate financial statements and close the ledger',false],
 ['Finance','Improve customer service and resolution time',true]
])test('the separated payroll duties retain their shared process scope '+department,()=>{const r=propose({department,strategyObjective:objective,responsibilities:'Prepare monthly payroll; reconcile GOSI contributions; calculate end of service benefits'});assert.equal(r.candidate.family,'hc');assert.equal(r.candidate.intent,'payroll');assert.equal(r.candidate.level,'specialist');assert.equal(r.detection.conflict,conflict);assert.equal(r.detection.evidenceSource,'responsibilities');});
test('an unrelated objective does not contaminate genuinely mixed payroll-cost duties',()=>{const r=propose({department:'Finance',strategyObjective:'Improve nursing care plans and monitor patient vital signs',responsibilities:'Analyze payroll cost against the annual budget; forecast monthly costs and explain variances; process employee payroll and reconcile payslips'});assert.equal(r.candidate.family,'finance');assert.equal(r.candidate.intent,'cost');assert.equal(r.detection.conflict,true);assert.deepEqual(new Set(r.detection.workstreams.map(x=>x.family.id)),new Set(['finance','hc']));});
test('strategic leadership goals cannot inflate the level of separated contributor duties',()=>{const r=propose({department:'Finance',strategyObjective:'Lead a team of 40 accountants; approve financial statements for the board',responsibilities:'Prepare accounting entries; reconcile bank accounts'});assert.equal(r.candidate.level,'specialist');assert.equal(r.directReports,null);assert.equal(r.levelAnalysis.evidence.people.length,0);});
for(const duties of ['Manage key accounts\nBuild sales pipeline\nNegotiate contracts\nReport monthly forecasts','Manage customer accounts\nDevelop sales opportunities\nReport monthly forecasts'])test('commercial account ownership establishes a second Sales duty '+duties.split('\n')[0],()=>{const r=propose({strategyObjective:'Increase regional sales revenue by 20%',responsibilities:duties});assert.equal(r.candidate.family,'sales');assert.equal(r.candidate.level,'specialist');assert.ok(r.detection.evidence.specialtyClauses>=2);});
test('Arabic strategic customer accounts remain a commercial phrase',()=>{const r=propose({department:'المبيعات',responsibilities:'إدارة حسابات العملاء الرئيسية؛ تطوير فرص البيع؛ رفع التوقعات الشهرية'});assert.equal(r.candidate.family,'sales');assert.ok(r.detection.evidence.specialtyClauses>=2);});
for(const department of ['Sales','Unknown'])test('generic accounts, contracts and forecasts cannot establish Sales '+department,()=>{const input={department,strategyObjective:'Increase regional sales revenue by 20%',responsibilities:'Manage accounts; negotiate contracts; report monthly forecasts'};if(R.detect(input)?.fieldFamily){assert.equal(propose(input).status,'needs-confirmation');assert.equal(propose(input).finalTitle,null);}else{assert.equal(propose(input),null);assert.throws(()=>R.validateScope(input),e=>e.code==='MIYAR_UNSUPPORTED_SCOPE');}});
test('accounting duties retain Finance while handling generic accounts and forecasts',()=>{const r=propose({department:'Finance',responsibilities:'Prepare accounting entries; reconcile bank accounts; manage accounts; report monthly forecasts'});assert.equal(r.candidate.family,'finance');assert.equal(r.detection.workstreams.some(x=>x.family.id==='sales'),false);});
