'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),R=require('../dist/role-recommender.js');
const nodes=require('../dist/classifications/ssco-2019.json').nodes,education=require('../dist/classifications/education-2020.json').fields;
const propose=input=>R.recommend(input,nodes,education);
// Additional authored counterexamples. They are not the independent golden set.
for(const [text,count,want]of [
 ['Oversee a group of 7 auditors and sign off internal audit plans',7,'manager'],
 ['Manage a unit of 18 analysts; approve financial statements',18,'director'],
 ['قيادة وحدة من ٧ محاسبين؛ اعتماد إقفال الحسابات',7,'manager'],
 ['يدير قسمًا من ١٨ محاسبًا؛ يعتمد القوائم المالية',18,'director']
])test('general people evidence: '+text,()=>{const r=R.analyzeLevel({responsibilities:text});assert.equal(r.level,want);assert.equal(r.directReports,count);assert.ok(r.evidence.people.length);assert.ok(r.evidence.approval.length);});
for(const [title,want]of [['Head of Compliance','director'],['Director of Human Resources','director'],['مدير إدارة المالية','director'],['مدير الموارد البشرية','manager']])test('own title retains hierarchy: '+title,()=>assert.equal(R.level({title}),want));
for(const text of ['Prepare accounting entries and report findings to the Chief Executive','إعداد القيود المحاسبية ورفع التقارير للرئيس التنفيذي','Review investment opportunities without leading a team of 22 analysts'])test('recipient/excluded titles do not confer rank: '+text,()=>{const r=R.analyzeLevel({responsibilities:text});assert.equal(r.level,'specialist');assert.equal(r.directReports,null);});
test('explicit specialist cannot publish a role with conflicting people-and-approval evidence',()=>{const r=propose({department:'Finance',seniority:'specialist',responsibilities:'Manage a team of 9 accountants; approve accounting entries; review bank reconciliations'});assert.equal(r.status,'blocked');assert.equal(r.finalTitle,null);assert.equal(r.levelAnalysis.leadershipConflict,true);});
test('two meaningful clauses do not require newlines',()=>{const r=propose({department:'Internal Audit',responsibilities:'Test controls and document audit evidence and monitor audit findings'});assert.equal(r.candidate.family,'internalAudit');assert.ok(r.detection.evidence.specialtyClauses>=2);});
test('one repeated specialized clause cannot manufacture two duties',()=>{const input={department:'Finance',responsibilities:'Prepare accounting entries; prepare accounting entries; prepare a report'};assert.equal(propose(input),null);assert.throws(()=>R.validateScope(input),/insufficient/i);});
test('shared commercial words do not select a specialty even with Finance selected',()=>{const input={department:'Finance',responsibilities:'Review cost reports; update budget reports; prepare reports'};assert.equal(propose(input),null);});
test('routine payable records retain a clerk and relevant metrics',()=>{const r=propose({department:'Finance',responsibilities:'Enter vendor invoices; match supplier invoices; archive invoice evidence'});assert.equal(r.candidate.level,'assistant');assert.match(r.candidate.titleEn,/Clerk/);assert.doesNotMatch(r.candidate.titleEn,/Analyst|Manager/);assert.match(r.candidate.metricEn,/invoices/i);});
for(const [department,responsibilities]of [
 ['Security','Conduct security patrols; verify visitor access; document access control exceptions'],
 ['الأمن والسلامة','تنفيذ جولات أمنية؛ فحص معدات الوقاية؛ تنسيق الإخلاء']
])test('security and safety retain licensing review: '+department,()=>{const r=propose({department,responsibilities});assert.equal(r.candidate.family,'securitySafety');assert.equal(r.checks.find(x=>x.id==='license').status,'warn');assert.match(r.candidate.skillsEn.join(' '),/Access|hazard|Safety/i);});
test('physical repair work never receives an engineer title from an explicit specialist request',()=>{const r=propose({department:'Maintenance',requestedLevel:'specialist',responsibilities:'Inspect HVAC preventive maintenance; repair electrical faults; document work orders'});assert.equal(r.candidate.level,'technician');assert.doesNotMatch(r.candidate.titleEn,/Engineer/);});
test('all added occupational links point to real supplied codes and pages',()=>{for(const r of R.catalog.roles){const source=nodes.find(x=>x.level==='occupation'&&x.code===r.ssco);assert.ok(source,r.titleEn);assert.equal(source.sourcePage,r.sourcePage,r.titleEn);for(const code of r.educationCodes)assert.ok(education.some(x=>x.code===code),r.titleEn+' '+code);}});
test('an independently owned leadership duty after a recipient survives context removal',()=>{const r=propose({department:'Finance',responsibilities:'Report findings to the Finance Director and supervise a team of 8 accountants and approve accounting entries and review bank reconciliations'});assert.equal(r.candidate.level,'manager');assert.equal(r.directReports,8);assert.doesNotMatch(r.detection.text,/Finance Director/);assert.match(r.detection.text,/supervise a team/);});
test('cybersecurity tasks do not acquire physical-security licensing scope',()=>{const r=propose({department:'Information Technology',responsibilities:'Monitor cyber security controls; assess information security risk'});assert.equal(r.candidate.family,'it');assert.equal(r.detection.workstreams.some(x=>x.family.id==='securitySafety'),false);assert.equal(r.checks.some(x=>x.id==='license'),false);});
test('a no-management constraint cannot silently erase explicitly owned people leadership',()=>{const r=propose({department:'Finance',constraints:'no management duties',responsibilities:'Lead a team of 8 accountants; approve accounting entries; review bank reconciliations'});assert.equal(r.status,'blocked');assert.equal(r.finalTitle,null);assert.equal(r.checks.find(x=>x.id==='leadership').status,'fail');});
