const test=require('node:test'),assert=require('node:assert/strict');
const R=require('../dist/role-recommender'),C=require('../dist/enterprise-core'),F=require('../dist/classifications/framework-example.json'),ref=require('../dist/classifications/ssco-2019.json');
// New phrasing written for this release; public regression data, not an independent expert holdout.
const cases=[
 ['264301','ترجمة تقارير المؤسسة مع مراجعة المصطلحات في النسختين','Translate company reports and proofread translations for terminology consistency'],
 ['264301','ترجمة العقود وتوحيد المصطلحات في الوثائق الثنائية اللغة','Translate contracts and maintain bilingual terminology in documents'],
 ['241206','مراجعة أرصدة المخزون وتسوية نتائج الجرد الدوري','Reconcile inventory balances and conduct cycle counts'],
 ['241206','تحديد مستويات المخزون ومراقبة نقاط إعادة الطلب','Monitor stock levels and update reorder points'],
 ['251204','بناء تطبيقات الهاتف واختبار واجهات المستخدم قبل الإصدار','Develop mobile apps and test user interfaces before release'],
 ['251204','تطوير تطبيقات الجوال ومراجعة الشفرة واختبار الإصدار','Build mobile applications, review source code and run automated tests'],
 ['832201','قيادة سيارة المدير ونقل الركاب بأمان','Drive the chief executive car and transport passengers safely'],
 ['832201','قيادة سيارة الشركة وتوصيل الركاب وفق جدول الرحلات','Drive a company car and complete passenger transport on schedule']
];
for(const [code,ar,en] of cases)test('v7 unseen phrasing parity: '+en,()=>{for(const [objective,locale]of[[ar,'ar'],[en,'en']]){const result=R.recommend({objective,locale});assert.equal(result.status,'proposed-for-review',objective);assert.equal(result.candidate.ssco,code,objective);}});
for(const [ar,en]of[['خفض غياب الموظفين','Reduce employee absenteeism'],['خفض التكاليف','We need to cut costs'],['تحسين الإنتاجية','Increase productivity']])test('business outcome needs work clarification: '+en,()=>{for(const objective of[ar,en]){const r=R.recommend({objective});assert.equal(r.status,'needs-confirmation');assert.equal(r.clarificationKind,'work-design');assert.equal(r.candidate,null);}});
test('Director General, HR abbreviations and catalog occupation aliases remain code-bound',()=>{for(const [title,code]of[['Director General','112002'],['HR Manager','121202'],['HR Operations Specialist','242303'],['Inventory Specialist','241206'],['Translator','264301']])assert.equal(R.matchTitleCode(title,code,ref.nodes).status,'matched',title);assert.equal(R.matchTitleCode('HR Manager','251204',ref.nodes).status,'inconsistent');});
test('self-cycle is not a grade inversion and declared direct reports reconcile with observed children',()=>{const r=C.diagnose([{positionId:'SELF',parentPositionId:'SELF',title:'Software Engineer',occupationCode:'251204',grade:'G06',directReports:'0'},{positionId:'ROOT',title:'Director General',occupationCode:'112002',grade:'G10',directReports:'4'},{positionId:'CHILD',parentPositionId:'ROOT',title:'Translator',occupationCode:'264301',grade:'G04',directReports:'0'}],ref.nodes);assert.ok(r.rows[0].flags.includes('hierarchy_cycle'));assert.ok(!r.rows[0].flags.includes('grade_inversion'));assert.equal(r.rows[1].actualDirectReports,1);assert.ok(r.rows[1].flags.includes('direct_reports_mismatch'));});
test('KPI baseline, target and duration each block opening, but draft validation stays available',()=>{const valid={outcome:'Reliable releases',metric:'Acceptance pass rate',baseline:'80%',target:'95%',duration:'90 days'};assert.equal(C.validateKpis([valid]),true);for(const key of ['baseline','target','duration'])assert.throws(()=>C.validateKpis([{...valid,[key]:''}]),e=>e.kpiErrors.some(x=>x.key===key));assert.throws(()=>C.validateKpis([]),/at least one KPI/);assert.doesNotThrow(()=>C.validatePosition({title:'Saved draft'}));});
test('evidence repeated across three factors is rejected after case and punctuation normalization',()=>{const a=Object.fromEntries(F.factors.map(f=>[f.id,'2'])),e=Object.fromEntries(F.factors.map(f=>[f.id,'Documented work requirement and explicitly delegated authority for '+f.id]));const repeated='Documented responsibility for software release approval and controlled access to systems';e.knowledge=repeated;e.complexity=repeated.toUpperCase();e.impact=repeated+'!';assert.throws(()=>C.validateEvaluation(F,a,e),err=>err.field==='impact'&&err.evidence);e.impact+=' under the service owner';assert.doesNotThrow(()=>C.validateEvaluation(F,a,e));});
