const {test,expect}=require('@playwright/test');
const {spawn}=require('node:child_process'),path=require('node:path');
const BASE=process.env.MIYAR_E2E_BASE||'http://127.0.0.1:4173/',API='http://127.0.0.1:8194';let server,logs='';
test.beforeAll(async()=>{
 server=spawn(process.env.MIYAR_TEST_PYTHON||'python3',['-m','uvicorn','e2e.fixtures.v7_governance_seed:app','--host','127.0.0.1','--port','8194'],{cwd:path.join(__dirname,'..'),env:{...process.env,MIYAR_ENV:'test'}});server.stdout.on('data',x=>logs+=x);server.stderr.on('data',x=>logs+=x);
 for(let i=0;i<150;i++){try{if((await fetch(API+'/health')).ok)return;}catch{}if(server.exitCode!==null)throw Error(logs);await new Promise(r=>setTimeout(r,200));}throw Error('Isolated v7 API did not start: '+logs);
});
test.afterAll(()=>server?.kill());test.afterEach(async({page})=>page.unrouteAll({behavior:'ignoreErrors'}));
async function login(page,email){await page.addInitScript(()=>localStorage.setItem('miyar-language','en'));await page.route('https://miyar-enterprise-api.onrender.com/**',async r=>r.fulfill({response:await r.fetch({url:r.request().url().replace('https://miyar-enterprise-api.onrender.com',API)})}));await page.goto(BASE+'#enterprise/connection');await page.locator('#ent-email').fill(email);await page.locator('#ent-password').fill('isolated-test-password-928');await page.locator('#ent-login button[type=submit]').click();await page.waitForURL(/#enterprise\/overview$/);await page.goto(BASE+'#enterprise/workspace');}
test('v7 institution requester and repeated approver are blocked by server',async({page})=>{
 for(const [email,title,needle]of[['a-v7-self@audit.test','V7 overdue creator request','own'],['a-v7-approver@audit.test','V7 repeated approver request','two stages']]){
  await login(page,email);const row=page.locator('[data-position]').filter({hasText:title});await row.click();await expect(page.locator('#ent-position-detail h3')).toContainText(title);await expect(page.locator('#ent-approve')).toHaveCount(0);
  const id=await row.getAttribute('data-position'),response=page.waitForResponse(r=>r.url().endsWith('/positions/'+id+'/decisions')&&r.request().method()==='POST');const denied=await page.evaluate(async id=>{try{await window.MiyarEnterprise.request('/positions/'+id+'/decisions','POST',{revision:1,decision:'approve',comment:'Direct server permission check',evidence:{businessValidated:true,budgetOwnerConfirmed:true,headcountConfirmed:true,scopeReviewed:true,mappingReviewed:true,roleNotPerson:true}});return {message:'Unexpected approval'};}catch(e){return {message:e.message};}},id);
  const raw=await response;expect(raw.status()).toBe(403);expect((await raw.json()).detail.toLowerCase()).toContain(needle);
  await page.evaluate(()=>document.activeElement?.blur());await page.locator('#ent-position-detail').screenshot({path:'test-results/v7-institution-'+(email.includes('self')?'requester':'repeated-approver')+'.png'});
  await page.goto(BASE+'#enterprise/connection');await page.locator('#ent-logout').click();
 }
});
test('v7 institution overdue request escalates automatically and unchanged replacement skips evaluation',async({page})=>{
 await login(page,'a-chro@audit.test');const overdue=page.locator('[data-position]').filter({hasText:'V7 overdue creator request'});await overdue.click();await expect(page.locator('.ent-stage-deadline')).toContainText('Approval SLA exceeded');
 const id=await overdue.getAttribute('data-position');const position=await page.evaluate(id=>window.MiyarEnterprise.request('/positions/'+id),id);expect(position.workflow[position.approvalStage].escalatedAt).toBeTruthy();
 await page.evaluate(()=>document.activeElement?.blur());await page.locator('#ent-position-detail').screenshot({path:'test-results/v7-institution-sla.png'});await page.goto(BASE+'#enterprise/connection');await page.locator('#ent-logout').click();await login(page,'a-total_rewards@audit.test');
 const candidates=await page.evaluate(()=>window.MiyarEnterprise.request('/positions?limit=100&offset=0'));const replacement=candidates.items.find(p=>p.content?.requestType==='replacement');expect(replacement).toBeTruthy();await page.locator('[data-position="'+replacement.id+'"]').click();
 await expect(page.locator('#ent-approval-form')).toContainText('no new evaluation is required');await expect(page.locator('#ent-record-grade')).toHaveCount(0);
 const response=page.waitForResponse(r=>r.url().endsWith('/positions/'+replacement.id+'/evaluation')&&r.request().method()==='POST');await page.evaluate(async id=>{try{await window.MiyarEnterprise.request('/positions/'+id+'/evaluation','POST',{revision:1,answers:{},evidence:{}});}catch{}},replacement.id);const raw=await response;expect(raw.status()).toBe(409);expect((await raw.json()).detail).toContain('no new evaluation is required');
 await page.locator('[data-evidence="payFrameworkReviewed"]').check();await page.locator('#ent-review-comment').fill('Reviewed unchanged funded replacement and reused approved evaluation');await page.evaluate(()=>document.activeElement?.blur());await page.locator('#ent-position-detail').screenshot({path:'test-results/v7-institution-replacement.png'});await page.locator('#ent-approve').click();await expect(page.locator('#ent-approve')).toHaveCount(0);
 const approvals=await page.evaluate(id=>window.MiyarEnterprise.request('/positions/'+id+'/approvals'),replacement.id);expect(approvals.find(a=>a.role==='total_rewards').evidence.evaluationReuse.evaluationId).toBeTruthy();
});
test('v7 authenticated approved position and grade survive compensation reload',async({page})=>{
 await login(page,'a-chro@audit.test');const positions=await page.evaluate(()=>window.MiyarEnterprise.request('/positions?limit=100&offset=0')),source=positions.items.find(p=>p.state==='active');expect(source).toBeTruthy();await page.locator('[data-position="'+source.id+'"]').click();await page.goto(BASE+'#enterprise/compensation');await expect(page.locator('#cp-position')).toHaveValue(source.id);const grade=await page.locator('#cp-grade').inputValue();expect(grade).toBeTruthy();
 await expect(page.locator('#cp-mid')).toHaveValue('20000');await page.locator('[data-cp-cost-panel] > summary').click();await page.locator('#cp-oncost').fill('15');await page.locator('[data-cp-run]').click();await expect(page.locator('.cp-result')).toContainText('276,000');await page.reload();await page.goto(BASE+'#enterprise/connection');await page.locator('#ent-email').fill('a-chro@audit.test');await page.locator('#ent-password').fill('isolated-test-password-928');await page.locator('#ent-login button[type=submit]').click();await page.waitForURL(/#enterprise\/overview$/);await page.goto(BASE+'#enterprise/compensation');await expect(page.locator('#cp-position')).toHaveValue(source.id);await expect(page.locator('#cp-grade')).toHaveValue(grade);await expect(page.locator('#cp-oncost')).toHaveValue('15');
});
