const {test,expect}=require('@playwright/test');
const BASE='http://127.0.0.1:4173/';
async function open(page,locale){await page.addInitScript(locale=>localStorage.setItem('miyar-language',locale),locale);await page.route('https://miyar-enterprise-api.onrender.com/**',r=>r.fulfill({status:401,json:{detail:'Guest acceptance'}}));await page.goto(BASE+'#enterprise/manpower');await expect(page.locator('[data-mp-run]')).toBeVisible();}
const numeric=text=>Number(text.replace(/[٠-٩]/g,c=>'٠١٢٣٤٥٦٧٨٩'.indexOf(c)).replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c)).replace(/٫/g,'.').replace(/[٬,\s\u061c\u200e\u200f]/g,''));
async function baseSupply(page){return numeric(await page.locator('.mp-scenarios .mp-scenario').nth(1).locator(':scope > div').nth(0).locator('b').innerText());}
async function baseGap(page){return numeric(await page.locator('.mp-scenarios .mp-scenario').nth(1).locator(':scope > div').nth(1).locator('b').innerText());}
for(const locale of ['ar','en']){
 test('manpower 6.3.3 '+locale+': example percentages and supply agree across card, annual table and bridge',async({page})=>{await open(page,locale);await page.locator('[data-mp-example]').click();await expect(page.locator('#mp-high-demand')).toHaveValue('110');await page.locator('[data-mp-run]').click();await expect(page.locator('.mp-results')).toBeVisible();const card=await baseSupply(page),table=numeric(await page.locator('.mp-table-wrap tbody tr').last().locator('td').nth(4).innerText()),bridge=numeric(await page.locator('.mp-bridge li').nth(4).locator('b').innerText());expect(card).toBe(1.71);expect(table).toBe(card);expect(bridge).toBe(card);await expect(page.locator('[data-mp-planning-options]')).not.toHaveAttribute('open','');await expect(page.locator('#mp-current-hint')).toContainText(locale==='ar'?'حتى لا تطلب تعيينات':'so you do not hire');await expect(page.locator('.mp-model-notice')).toContainText(locale==='ar'?'الأدوار المعرفية والإشرافية':'Knowledge and supervisory roles');});
 test('manpower 6.3.3 '+locale+': hiring lead days and new-hire attrition reduce real calculated capacity',async({page})=>{await open(page,locale);await page.locator('[data-mp-example]').click();await page.locator('[data-mp-planning-options] > summary').click();for(const [id,value] of Object.entries({target:'200',capacity:'50',current:'2',horizon:'1',attrition:'0',involuntary:'0','new-attrition':'0',productivity:'0',hires:'2','hire-days':'0'}))await page.locator('#mp-'+id).fill(value);await page.locator('[data-mp-run]').click();expect(await baseSupply(page)).toBe(4);expect(await baseGap(page)).toBe(0);await page.locator('#mp-hire-days').fill('120');await page.locator('[data-mp-run]').click();const delayedSupply=await baseSupply(page);expect(delayedSupply).toBe(3.34);expect(await baseGap(page)).toBe(.66);await page.locator('#mp-new-attrition').fill('25');await page.locator('[data-mp-run]').click();expect(await baseSupply(page)).toBeLessThan(delayedSupply);expect(await baseGap(page)).toBeGreaterThan(.66);});
 test('manpower 6.3.3 '+locale+': invalid first-year attrition focuses exact field with adjacent accessible error',async({page})=>{await open(page,locale);await page.locator('[data-mp-example]').click();await page.locator('[data-mp-planning-options] > summary').click();await page.locator('#mp-new-attrition').fill('');await page.locator('[data-mp-planning-options] > summary').click();await page.locator('[data-mp-run]').click();await expect(page.locator('[data-mp-planning-options]')).toHaveAttribute('open','');await expect(page.locator('#mp-new-attrition')).toBeFocused();await expect(page.locator('#mp-new-attrition')).toHaveAttribute('aria-invalid','true');await expect(page.locator('#mp-new-attrition')).toHaveAttribute('aria-describedby',/mp-input-error/);await expect(page.locator('.mp-run [data-mp-message]')).toHaveAttribute('data-state','error');await expect(page.locator('.mp-results')).toHaveCount(0);});
}
test('manpower 6.3.3: visible compensation journey imports matching employer cost and clears it when grade changes',async({page})=>{
 await open(page,'en');await page.locator('[data-mp-example]').click();await page.locator('[data-mp-context-options] > summary').click();await page.locator('#mp-grade').fill('G11');await page.locator('[data-mp-run]').click();await page.locator('[data-cp-from-mp]').click();await expect(page.locator('#cp-role')).toHaveValue('Human Capital Projects & Operations Manager');await expect(page.locator('#cp-grade')).toHaveValue('G11');for(const selector of ['[data-cp-position-panel]','[data-cp-cost-panel]','[data-cp-progression-panel]'])if(await page.locator(selector).getAttribute('open')===null)await page.locator(selector+' > summary').click();for(const [id,value] of Object.entries({min:'10000',mid:'12500',max:'15000',source:'Synthetic browser test band',currency:'SAR',headcount:'1',target:'100',current:'',oncost:'10',allowances:'0'}))await page.locator('#cp-'+id).fill(value);await page.locator('[data-cp-run]').click();await expect(page.locator('.cp-result')).toBeVisible();await expect(page.locator('.cp-metrics').locator('div').last()).toContainText('165,000');await page.goto(BASE+'#enterprise/manpower');await expect(page.locator('#mp-grade')).toHaveValue('G11');await page.locator('[data-mp-import-cost]').click();await expect(page.locator('#mp-cost')).toHaveValue('165000');await expect(page.locator('[data-mp-cost-note]')).toContainText('compensation result matching');await page.locator('[data-mp-run]').click();await expect(page.locator('.mp-results .mp-assumptions').locator('div').last()).toContainText('165,000 SAR');await page.locator('[data-mp-context-options] > summary').click();await page.locator('#mp-grade').fill('G12');await expect(page.locator('#mp-cost')).toHaveValue('');await page.locator('[data-mp-import-cost]').click();await expect(page.locator('[data-mp-context-note]')).toContainText('No employer-cost result matches');await page.locator('#mp-grade').fill('G11');await page.locator('[data-mp-import-cost]').click();await expect(page.locator('#mp-cost')).toHaveValue('165000');await page.goto(BASE+'#enterprise/compensation');await page.locator('#cp-mid').fill('12600');await page.goto(BASE+'#enterprise/manpower');await expect(page.locator('#mp-cost')).toHaveValue('');await expect(page.locator('[data-mp-cost-note]')).not.toContainText('compensation result matching');await page.locator('#mp-cost').fill('123456');await page.goto(BASE+'#enterprise/compensation');await page.locator('#cp-mid').fill('12700');await page.goto(BASE+'#enterprise/manpower');await expect(page.locator('#mp-cost')).toHaveValue('123456');await expect(page.locator('[data-mp-cost-note]')).toContainText('Manually entered employer cost');
});

test('manpower UX: unsaved actual inputs survive navigation and language changes',async({page})=>{await open(page,'en');await page.locator('[data-mp-example]').click();await page.locator('#mp-current').fill('3.5');await page.locator('#mp-target').fill('240');await page.locator('[data-mp-context-options] > summary').click();await page.locator('#mp-role').fill('Manual planning scope');await page.locator('#mp-grade').fill('G07');await page.locator('#language-btn').click();await expect(page.locator('#mp-current')).toHaveValue('3.5');await expect(page.locator('#mp-target')).toHaveValue('240');await expect(page.locator('#mp-role')).toHaveValue('Manual planning scope');await expect(page.locator('#mp-grade')).toHaveValue('G07');await page.goto(BASE+'#enterprise/compensation');await expect(page.locator('[data-cp-run]')).toBeVisible();await page.goto(BASE+'#enterprise/manpower');await expect(page.locator('#mp-current')).toHaveValue('3.5');await expect(page.locator('#mp-target')).toHaveValue('240');await expect(page.locator('#mp-role')).toHaveValue('Manual planning scope');});
