const {test,expect}=require('@playwright/test');
for(const locale of ['ar','en'])test('guided position suggests source-linked fields, preserves edits and reveals validation / '+locale,async({page})=>{
 const ar=locale==='ar',manualTitle=ar?'مسماي المخصص للمراجعة':'My custom position title';
 await page.addInitScript(locale=>localStorage.setItem('miyar-language',locale),locale);
 await page.route('https://miyar-enterprise-api.onrender.com/**',r=>r.fulfill({status:401,json:{detail:'Local acceptance'}}));
 await page.goto('http://127.0.0.1:4173/#enterprise/create');
 for(const key of ['businessNeed','responsibilities','title','successMeasures'])await expect(page.locator('#ent-position-start [data-field='+key+']')).toBeVisible();
 await expect(page.locator('#ent-position-start .ent-form-grid > label')).toHaveCount(4);
 await expect(page.locator('[data-od-strategy]')).toHaveCount(1);await expect(page.locator('[data-od-responsibilities]')).toHaveCount(1);
 for(const id of ['identity','scope','budget'])await expect(page.locator('#ent-position-'+id)).not.toHaveAttribute('open','');
 await page.locator('[data-field=businessNeed]').fill(ar?'تطوير الخدمات البرمجية الداخلية':'Deliver internal software services');
 await page.locator('[data-field=responsibilities]').fill(ar?'تطوير خصائص برمجية؛ مراجعة الكود؛ تنفيذ اختبارات آلية':'Develop software features; perform code review; run automated tests');
 await expect(page.locator('[data-field=occupationCode]')).toHaveValue('251204');await expect(page.locator('[data-field=educationFieldCode]')).toHaveValue('061302');
 await expect(page.locator('[data-field=qualifications]')).toHaveValue(ar?/هندسة البرمجيات|البرمجة/:/IT|computer science/);
 await expect(page.locator('#ent-guided-status')).toContainText(ar?'قابلة للتعديل':'Editable');
 await page.locator('#ent-guided-proposals > details > summary').click();await expect(page.locator('#ent-guided-proposals')).toContainText('SSCO 2019');await expect(page.locator('#ent-guided-proposals')).toContainText('251204');await expect(page.locator('#ent-guided-proposals')).toContainText('63');
 for(const selector of ['[data-field=salaryGrade]','[data-number=annualCost]','[data-number=directReports]','[data-field=authority]'])await expect(page.locator(selector)).toHaveValue('');
 for(const key of ['baseline','target','duration'])await expect(page.locator('[data-matrix-key=kpis][data-matrix-field='+key+']')).toHaveValue('');
 await page.locator('[data-field=title]').fill(manualTitle);
 await page.locator('[data-field=businessNeed]').fill(ar?'ضبط إقفال الحسابات المالية':'Close financial accounts');
 await page.locator('[data-field=responsibilities]').fill(ar?'إعداد القيود المحاسبية؛ تسوية الحسابات البنكية؛ مراجعة القوائم المالية':'Prepare accounting entries; reconcile bank accounts; review financial statements');
 await expect(page.locator('[data-field=occupationCode]')).toHaveValue('241101');await expect(page.locator('[data-field=title]')).toHaveValue(manualTitle);
 await expect(page.locator('#ent-guided-proposals')).toContainText('241101');await expect(page.locator('#ent-guided-proposals')).not.toContainText('251204');
 await page.locator('[data-field=businessNeed]').fill('zxqv qqqz');await page.locator('[data-field=responsibilities]').fill('zxqv qqqz');
 await expect(page.locator('[data-field=occupationCode]')).toHaveValue('');await expect(page.locator('[data-field=educationFieldCode]')).toHaveValue('');await expect(page.locator('#ent-guided-proposals')).toBeEmpty();await expect(page.locator('[data-field=title]')).toHaveValue(manualTitle);
 await page.locator('#ent-show-position-fields').click();for(const id of ['identity','scope','budget'])await expect(page.locator('#ent-position-'+id)).toHaveAttribute('open','');
 await page.locator('[data-number=headcount]').fill('0');await page.locator('#ent-position-budget > summary').click();await page.locator('#ent-save').click();
 await expect(page.locator('#ent-position-budget')).toHaveAttribute('open','');await expect(page.locator('[data-number=headcount]')).toBeFocused();await expect(page.locator('[data-number=headcount]')).toHaveAttribute('aria-invalid','true');
});
