const {test,expect}=require('@playwright/test');
for(const locale of ['ar','en'])test('Quick Trial explains input, suggests editable context and opens AI fields / '+locale,async({page})=>{
 await page.addInitScript(locale=>localStorage.setItem('miyar-language',locale),locale);
 await page.route('https://miyar-enterprise-api.onrender.com/**',r=>r.fulfill({status:401,json:{detail:'Local acceptance'}}));
 await page.goto('http://127.0.0.1:4173/#demo');
 await page.locator('#objective').fill('');await page.locator('#role-form button[type=submit]').click();await expect(page.locator('#objective')).toBeFocused();await expect(page.locator('#objective')).toHaveAttribute('aria-invalid','true');await expect(page.locator('#objective')).toHaveAttribute('aria-describedby',/form-error/);await expect(page.locator('#form-error')).toBeVisible();
 const details=page.locator('#demo-context-fields');await expect(details).not.toHaveAttribute('open','');await expect(page.locator('#domain')).not.toBeVisible();await expect(page.locator('#objective-purpose')).toContainText(locale==='ar'?'لماذا':'Why');
 await page.locator('#objective').fill(locale==='ar'?'تطوير تطبيقات الويب وكتابة الكود':'Develop web applications and write source code');await expect(page.locator('#form-error')).not.toBeVisible();await expect(page.locator('#objective')).not.toHaveAttribute('aria-invalid','true');await page.locator('#role-form button[type=submit]').click();
 await expect(page.locator('.demo-v5-primary-source')).toContainText('251204');await expect(page.locator('#demo-suggested-context')).toContainText('SSCO 2019');await expect(page.locator('#domain')).toHaveValue(locale==='ar'?'تقنية المعلومات':'Information Technology');await expect(page.locator('#seniority')).toHaveValue('');await expect(page.locator('#constraints')).toHaveValue('');
 await page.locator('#objective').fill(locale==='ar'?'إعداد القوائم المالية وتسوية الحسابات':'Prepare financial statements and reconcile accounting balances');await expect(page.locator('#domain')).toHaveValue('');await page.locator('#role-form button[type=submit]').click();await expect(page.locator('.demo-v5-primary-source')).toContainText('241101');await expect(page.locator('#domain')).toHaveValue(locale==='ar'?'المالية':'Finance');
 await page.locator('#objective').fill('asdf qwer zxcv');await expect(page.locator('#domain')).toHaveValue('');await page.locator('#role-form button[type=submit]').click();await expect(page.locator('.demo-final-title')).toHaveCount(0);await expect(page.locator('#demo-suggested-context')).not.toBeVisible();
 await page.locator('#objective').fill(locale==='ar'?'تطوير تطبيقات الويب وكتابة الكود':'Develop web applications and write source code');await page.locator('#role-form button[type=submit]').click();await expect(page.locator('.demo-v5-primary-source')).toContainText('251204');
 await page.locator('[data-demo-edit-context]').click();await expect(page.locator('#domain')).toBeFocused();await expect(page.locator('#demo-domain-purpose')).toContainText(locale==='ar'?'لماذا':'Why');
 await page.locator('#domain').fill('Information Technology / product team');await page.locator('#role-form button[type=submit]').click();await expect(page.locator('.demo-v5-primary-source')).toContainText('251204');await expect(page.locator('#domain')).toHaveValue('Information Technology / product team');
 await page.route('**/api/v1/analyze/strategic/status',r=>r.fulfill({json:{configured:true}}));
 await page.locator('#demo-context-fields > summary').click();await page.locator('#demo-engine-mode').selectOption('ai');await expect(page.locator('#seniority')).toBeVisible();await expect(page.locator('#seniority')).toHaveAttribute('aria-required','true');
 await page.locator('#demo-context-fields > summary').click();await page.locator('#role-form button[type=submit]').click();await expect(page.locator('#seniority')).toBeFocused();await expect(page.locator('#seniority')).toBeVisible();
});
for(const locale of ['ar','en'])test('ambiguity choices explain duties without creating evidence / '+locale,async({page})=>{
 await page.addInitScript(locale=>localStorage.setItem('miyar-language',locale),locale);await page.route('https://miyar-enterprise-api.onrender.com/**',r=>r.fulfill({status:401,json:{detail:'Local acceptance'}}));
 await page.goto('http://127.0.0.1:4173/#demo');await page.locator('#objective').fill(locale==='ar'?'توظيف مهندسي البرمجيات':'Recruit software engineers');await page.locator('#role-form button[type=submit]').click();
 const hints=page.locator('[data-confirm-role-purpose]');await expect(hints).toHaveCount(2);for(const hint of await hints.all())await expect(hint).toContainText(locale==='ar'?'اختره إذا':'Choose if');await expect(page.locator('#domain')).toHaveValue('');await expect(page.locator('#seniority')).toHaveValue('');await expect(page.locator('.demo-final-title')).toHaveCount(0);
});
