const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),zlib=require('node:zlib'),esbuild=require('esbuild');
const version=fs.readFileSync('VERSION','utf8').trim();if(!/^\d+\.\d+\.\d+$/.test(version))throw Error('Invalid VERSION');
let template=fs.readFileSync('web/index.template.html','utf8');
const scripts=[...template.matchAll(/<script defer src="\.\/([^?]+)\?[^\"]+"><\/script>/g)].map(m=>m[1]);
const styles=[...template.matchAll(/<link rel="stylesheet" href="\.\/([^?]+)\?[^\"]+">/g)].map(m=>m[1]);
scripts.push('audit-improvements.js');styles.push('audit-improvements.css','expert-landing.css','expert-workspace.css');
const all=[...scripts,...styles,'trust.js','trust.css','../server/requirements-lock.txt',...fs.readdirSync('server').filter(x=>x.endsWith('.py')).map(x=>'../server/'+x)];
const hash=crypto.createHash('sha256').update(version).update(template).update(fs.readFileSync('web/trust.template.html')).update(fs.readFileSync(__filename)).update(fs.readFileSync('dist/assets/arabic.woff2')); for(const f of all)hash.update(f).update(fs.readFileSync(path.join('dist',f)));const buildId=hash.digest('hex').slice(0,16);
const manifest={version,buildId,releasedAt:'2026-10-04',changes:['Refined bilingual experience: decision-first entrance, navy and teal identity, consistent forms and results, accessible RTL and responsive layouts','Enable locally hosted multilingual semantic occupation and skill matching',
    'Constrain semantic proposals by explicit source-checked field and level; show uncertainty for unsupported occupations','Enable validated Arabic and English AI KPI proposals','Resolve external sources and verify 44 official reference links','Functional acceptance: distinct-role approval workflows and inspected exports','Invalidate stale skill, bulk, pilot and imported scenario results','Clear corrected errors and require explicit finance approval inputs','Security updates to pinned API dependencies','Clear HR value proposition and complete service directory on the entrance','Returning-user updates moved after the primary value and start form','Zero-minimum compensation diagnostics and currency validation','Complete enterprise deep-link routing','Project Development, Investment, Internal Audit, Strategy and PMO recommendations shared by Quick Trial and OD','Complex-description context separation with reviewable tasks, recipients and exclusions','Bilingual HR service guides and authored skills for the added functions','What is new panel, New badges and a version badge for returning users','Guided 10-minute tour that loads labelled demo data','Plain decision summaries on planning and compensation results','Two-step sign-in, isolated demo tenant and AI window countdown (6.0.0)','Release-drift monitoring, secret scanning, CDN headers, share card and signature block (6.0.0)'],assets:{scripts,styles}};
fs.writeFileSync('dist/release.json',JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync('dist/release-config.js','window.MIYAR_RELEASE='+JSON.stringify(manifest)+';\n');
const js=esbuild.transformSync(fs.readFileSync('dist/release-config.js','utf8')+'\n'+scripts.map(f=>fs.readFileSync('dist/'+f,'utf8')).join('\n;\n'),{minify:true,target:'es2020',loader:'js',legalComments:'none',charset:'utf8'}).code;
const css=esbuild.transformSync(styles.map(f=>fs.readFileSync('dist/'+f,'utf8')).join('\n'),{minify:true,loader:'css',legalComments:'none',charset:'utf8'}).code;
for(const f of fs.readdirSync('dist'))if(/^miyar-(?:trust-)?[a-f0-9]+\.(js|css)$/.test(f))fs.unlinkSync('dist/'+f);
const trustJs=esbuild.transformSync(fs.readFileSync('dist/release-config.js','utf8')+'\n'+fs.readFileSync('dist/config.js','utf8')+'\n'+fs.readFileSync('dist/trust.js','utf8'),{minify:true,target:'es2020',loader:'js',legalComments:'none',charset:'utf8'}).code;
fs.writeFileSync('dist/miyar-trust-'+buildId+'.js',trustJs);fs.writeFileSync('dist/miyar-trust-'+buildId+'.css',fs.readFileSync('dist/trust.css','utf8'));
const trust=fs.readFileSync('web/trust.template.html','utf8').replace(/<script defer[^>]+><\/script>/g,'').replace('./trust.css','./miyar-trust-'+buildId+'.css').replace('</head>','<script defer src="./miyar-trust-'+buildId+'.js"></script></head>');fs.writeFileSync('dist/trust.html',trust);
fs.writeFileSync('dist/miyar-'+buildId+'.js',js);fs.writeFileSync('dist/miyar-'+buildId+'.css',css);
template=template.replace(/\n  <link rel="stylesheet"[^>]+>/g,'').replace(/\n  <script defer[^>]+><\/script>/g,'').replace(/5\.0\.6(?:\.1)?/g,version).replace('</head>','  <link rel="stylesheet" href="./miyar-'+buildId+'.css">\n  <script defer src="./miyar-'+buildId+'.js"></script>\n</head>');
const csp="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data: blob:; connect-src 'self' https://miyar-enterprise-api.onrender.com; object-src 'none'; base-uri 'self'; form-action 'self'";
template=template.replace('<meta charset="UTF-8">','<meta charset="UTF-8">\n  <meta http-equiv="Content-Security-Policy" content="'+csp+'">');
// Response headers for a configurable host/CDN (Cloudflare Pages, Netlify). GitHub Pages ignores this file; the meta CSP remains as defence in depth.
fs.writeFileSync('dist/_headers','/*\n  Strict-Transport-Security: max-age=31536000; includeSubDomains\n  Content-Security-Policy: '+csp+"; frame-ancestors 'none'\n  X-Frame-Options: DENY\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=()\n");
template=template.replace('</head>','  <script type="application/ld+json">'+fs.readFileSync('dist/structured-data.json','utf8').trim()+'</script>\n</head>');
fs.writeFileSync('dist/index.html',template);
const pkg=JSON.parse(fs.readFileSync('package.json'));pkg.version=version;pkg.scripts.build='node scripts/build-release.cjs';fs.writeFileSync('package.json',JSON.stringify(pkg,null,2)+'\n');const lock=JSON.parse(fs.readFileSync('package-lock.json'));lock.version=version;lock.packages[''].version=version;fs.writeFileSync('package-lock.json',JSON.stringify(lock,null,2)+'\n');
const estimate=zlib.gzipSync(js).length+zlib.gzipSync(css).length+zlib.gzipSync(template).length+fs.statSync('dist/assets/arabic.woff2').size+fs.statSync('dist/assets/favicon.svg').size;
console.log(JSON.stringify({version,buildId,compressedInitialBytes:estimate,referenceCorporaLoadedOnHome:false}));if(estimate>300000)throw Error('Initial asset budget exceeded (300 KB compressed estimate)');
